"""decode_handlers.py REPO TABLE_SYMBOL [COUNT] [OUT.c NATIVE_NAME]
Read a function-pointer table (u32 PS1 addresses) from BATTLE.BIN via the yaml symbol address, translate each entry to a
function name using target/battle.yaml, print the mapping, and optionally emit a C file defining a *native* table."""
import re, struct, sys
from pathlib import Path

repo = Path(sys.argv[1]); sym = sys.argv[2]
count = int(sys.argv[3]) if len(sys.argv) > 3 else 128
out_c, native = (sys.argv[4], sys.argv[5]) if len(sys.argv) > 5 else (None, None)

yaml = (repo / 'target' / 'battle.yaml').read_text().splitlines()
addr_of, fn_at, sym_addr = {}, {}, None
for l in yaml:
    m = re.match(r'\s*-\s*\{addr:\s*(0x[0-9a-fA-F]+),\s*size:\s*\d+,\s*name:\s*(\w+)', l)
    if m:
        fn_at[int(m.group(1), 16)] = m.group(2)
    m = re.match(r'\s*-\s*\{addr:\s*(0x[0-9a-fA-F]+),\s*name:\s*(\w+)\}', l)
    if m and m.group(2) == sym:
        sym_addr = int(m.group(1), 16)
if sym_addr is None:
    sys.exit(f'{sym} not found in battle.yaml')
data = (repo / 'build' / 'extracted' / 'files' / 'BATTLE.BIN').read_bytes()
off = sym_addr - 0x80067000
entries = struct.unpack_from(f'<{count}I', data, off)
names = []
for i, a in enumerate(entries):
    n = fn_at.get(a)
    names.append(n)
    if n is None and a != 0:
        # tolerate table running past its end
        pass
valid = [i for i, n in enumerate(names) if n]
print(f'{sym} @0x{sym_addr:08x}: {len(valid)} of {count} entries resolve to named functions')
for i in valid[:80]:
    print(f'  [{i:3d}] 0x{entries[i]:08x} {names[i]}')
if out_c:
    srcs = {p.stem for p in (repo / 'src').rglob('*.c')}
    used = [(i, names[i]) for i in valid if names[i] in srcs]
    lines = ['/* generated by decode_handlers.py: native version of ' + sym + ' */']
    for _, n in sorted(set(used), key=lambda t: t[1]):
        pass
    for n in sorted({n for _, n in used}):
        lines.append(f'extern void {n}(void);')
    lines.append(f'void (*{native}[{count}])(void) = {{')
    for i, n in used:
        lines.append(f'    [{i}] = {n},')
    lines.append('};')
    Path(out_c).write_text('\n'.join(lines) + '\n')
    print(f'wrote {out_c}: {len(used)} handlers')
