# Generic function-level differential fuzzer: every decompiled game function in src/main + src/battle whose signature can be
# called generically, native build vs the ORIGINAL machine code (R3000 interpreter), on random arguments.
#   .\port\native\fuzz.ps1 [-Trials 40] [-From 0] [-To 100000] [-AutoInit] [-DivFix] [-Sdk] [-Rebuild] [-Replay 'index,trial;index,trial'] [-Cflags '-DVERBOSE']
# PS1-address scheme: natively compiled functions are linked as native_<name>, the original names are bound to their PS1
# addresses and reached through x86 trampolines, so function pointers stored in RAM stay canonical PS1 addresses.
# -AutoInit  compile the game with -ftrivial-auto-var-init=zero (the recommended native flag: uninitialised locals read 0)
# -DivFix    give integer division MIPS semantics for zero and -1 divisors (tools/divfix.awk; see PORT-FEASIBILITY.md)
# -Sdk       also build and fuzz the reconstructed SDK libraries (libgpu, libc, libapi, libetc, libcd, libspu, libcard, libpress, suzuki)
# -Rebuild   recompile all game sources natively first (~1-2 min); done automatically when the flags change.
# Needs: port\build\portable (run .\port\probe.ps1 first), extracted disc files (fft_decomp\build\extracted), Docker.
param([int]$Trials = 40, [int]$From = 0, [int]$To = 100000, [switch]$AutoInit, [switch]$DivFix, [switch]$Sdk, [switch]$Rebuild, [string]$Replay = '', [string]$Cflags = '')
$root = Split-Path $PSScriptRoot -Parent
$repo = Join-Path (Split-Path $root -Parent) 'fft_decomp'
$nb   = Join-Path $root 'build\native'
New-Item -ItemType Directory -Force $nb | Out-Null
python (Join-Path $PSScriptRoot 'gen_symbols.py') $repo (Join-Path $nb 'symbols_pc.ld') --functions main.yaml battle.yaml | Out-Host
python (Join-Path $PSScriptRoot 'gen_funcs.py') $repo (Join-Path $nb 'func_addrs.c') main.yaml battle.yaml | Out-Host
python (Join-Path $PSScriptRoot 'gen_stubs.py') $repo (Join-Path $nb 'stub_table.c') --native-prefix=native_ main.yaml battle.yaml | Out-Host
# functions that can fall off the end of a non-void function: their return value is unspecified (tools/return_hazards.sh)
$rh = Join-Path $root 'build\return_hazards.txt'
if (-not (Test-Path $rh)) {
    docker run --rm --pull=never --volume "${root}:/port" fft-decomp-dev:local sh /port/tools/return_hazards.sh 2>$null | Set-Content -Path $rh
}
$rhNames = @(Get-Content $rh | Where-Object { $_ })
$rhLines = @('/* generated by fuzz.ps1 from build/return_hazards.txt */', 'const char* const g_unspecified_ret[] = {') + ($rhNames | ForEach-Object { '    "' + $_ + '",' }) + @('    0', '};')
[System.IO.File]::WriteAllText((Join-Path $nb 'unspecified_ret.c'), (($rhLines -join "`n") + "`n"))
$sdkArg = @()
$dirs = 'src/main src/battle'
if ($Sdk) { $sdkArg = @('--sdk'); $dirs = 'src/main src/battle src/psyq/libgpu src/psyq/libc src/psyq/libapi src/psyq/libetc src/psyq/libcd src/psyq/libspu src/psyq/libcard src/psyq/libpress src/psyq/suzuki' }
python (Join-Path $PSScriptRoot 'gen_fuzz.py') $repo $nb --native-prefix=native_ @sdkArg main.yaml battle.yaml | Out-Host
$gameFlags = ''
if ($AutoInit) { $gameFlags = '-ftrivial-auto-var-init=zero' }
if ($Replay) {                                     # 'index,trial' or 'index,trial;index,trial;...'
    $gameFlags = ("$gameFlags -finstrument-functions").Trim()
    $pairs = @($Replay -split ';' | Where-Object { $_ } | ForEach-Object { $p = $_ -split ','; "{ $($p[0]), $($p[1]) }," })
    [System.IO.File]::WriteAllText((Join-Path $nb 'replay_list.h'), (($pairs -join "`n") + "`n"))
    $Cflags = "$Cflags -DREPLAY_LIST_FILE"
}
$keyFile = Join-Path $nb 'all_pc\build_key.txt'
$divfixEnv = ""
if ($DivFix) { $divfixEnv = "1" }
$repHash = (Get-FileHash (Join-Path $PSScriptRoot 'replacements\replaced.txt') -Algorithm MD5).Hash
$key = "flags=$gameFlags divfix=$divfixEnv dirs=$dirs replaced=$repHash"
$have = ''
if (Test-Path $keyFile) { $have = (Get-Content $keyFile -Raw).Trim() }
if ($Rebuild -or $have -ne $key) {
    docker run --rm --pull=never -e "RENAME=1" -e "DIRS=$dirs" -e "DIVFIX=$divfixEnv" -e "OUT=/port/build/native/all_pc" -e "LDFILE=/port/build/native/symbols_pc.ld" -e "EXTRA_CFLAGS=$gameFlags" `
        --volume "${root}:/port" fft-decomp-dev:local sh /port/native/boundary.sh | Out-Host
    Set-Content -Path $keyFile -Value $key
}
docker run --rm --pull=never -e "DIVFIX=$divfixEnv" -e "EXTRA_CFLAGS=-DTRIALS=$Trials -DFROM=$From -DTO=$To $gameFlags $Cflags" `
    --volume "${root}:/port" --volume "$($repo)\build\extracted\files:/disc:ro" fft-decomp-dev:local `
    sh /port/native/build_run_fuzz.sh
