"""gen_funcs.py REPO OUT.c [module.yaml ...]  -- a C table {name, address, size} of every decompiled FUNCTION in the given
target/*.yaml files: the addresses of the ORIGINAL machine code, for the R3000 oracle to call (name clashes across modules
are resolved in file order, so pass main.yaml first)."""
import re, sys
from pathlib import Path
repo, out = Path(sys.argv[1]), sys.argv[2]
mods = sys.argv[3:] or ['main.yaml', 'battle.yaml']
sys.path.insert(0, str(Path(__file__).resolve().parent))
import yamlfuncs
seen, lines = set(), []
for m in mods:
    for addr, size, name, asm in yamlfuncs.module_functions(repo / 'target' / m):
        if name in seen:
            continue
        seen.add(name)
        lines.append(f'    {{ "{name}", 0x{addr:08x}u, {size}u }},')
Path(out).write_bytes((
    '/* generated by gen_funcs.py -- addresses of the original machine code */\n'
    'struct orig_func { const char* name; unsigned int addr; unsigned int size; };\n'
    'const struct orig_func g_orig_funcs[] = {\n' + '\n'.join(lines) + '\n    { 0, 0, 0 }\n};\n'
    f'const int g_orig_func_count = {len(lines)};\n').encode())
# the plain list of function names (used to rename natively compiled definitions to native_<name>)
names = [r.group(1) for r in (re.match(r'\s*\{ "(\w+)"', l) for l in lines) if r]
Path(out).with_name('fn_names.txt').write_bytes(('\n'.join(names) + '\n').encode())
print(f'{len(lines)} functions -> {out} (+ fn_names.txt)')
