"""gen_stubs.py REPO OUT.c [--native-prefix=native_] [module.yaml ...]  -- a table {PS1 address, size, native function} for every
decompiled function of the given modules. The natives are WEAK references: a function that is not linked into the program has a
null pointer and gets no trampoline. The runtime writes an x86 `jmp` at each PS1 address so that function pointers stored in the
game's data (formula tables, callbacks) -- which hold PS1 addresses -- land on the native code.

--native-prefix: the natively compiled definitions carry this prefix (PS1-address scheme, see gen_symbols.py --functions)."""
import re, sys
from pathlib import Path

args = sys.argv[1:]
prefix = ''
for a in list(args):
    if a.startswith('--native-prefix='):
        prefix = a.split('=', 1)[1]
        args.remove(a)
repo, out = Path(args[0]), args[1]
mods = args[2:] or ['main.yaml', 'battle.yaml']
sys.path.insert(0, str(Path(__file__).resolve().parent))
import yamlfuncs
seen, entries = set(), []
for m in mods:
    for addr, size, name, asm in yamlfuncs.module_functions(repo / 'target' / m):
        if name not in seen:
            seen.add(name)
            entries.append((addr, size, name))
lines = ['/* generated by gen_stubs.py */',
         'struct native_stub { unsigned int ps1_addr; unsigned int size; void* native; };']
for _, _, n in entries:
    lines.append(f'extern char {prefix}{n}[] __attribute__((weak));')
lines.append('const struct native_stub g_native_stubs[] = {')
for a, s, n in entries:
    lines.append(f'    {{ 0x{a:08x}u, {s}u, (void*){prefix}{n} }},')
lines.append('    { 0, 0, 0 }')
lines.append('};')
lines.append(f'const int g_native_stub_count = {len(entries)};')
Path(out).write_bytes(('\n'.join(lines) + '\n').encode())
print(f'{len(entries)} function stubs -> {out}' + (f' (natives named {prefix}<name>)' if prefix else ''))
