"""gen_hle.py REPO OUT.c

Generates OUT.c for the lockstep runtime: for every SDK function the HLE takes over (see hle/hle.h) a native entry point
`native_<name>(a, b, c, d)` that forwards to hle_call() on the native machine's hle_t, and the list of those names for the
interpreter side (which intercepts the original entry addresses instead).

Taken over: every function in the libspu / libetc / libcd / libcard address ranges of main.yaml, plus HLE_EXPLICIT_NAMES from hle/hle.h
(BIOS event API, hardware-facing libgpu entry points)."""
import re, sys
from pathlib import Path

repo, out = Path(sys.argv[1]), Path(sys.argv[2])
sys.path.insert(0, str(Path(__file__).resolve().parent))
import yamlfuncs

main = repo / 'target' / 'main.yaml'
ranges = {}
in_libs = False
for line in main.read_text().splitlines():
    if line.startswith('libraries:'):
        in_libs = True
        continue
    if line.startswith('functions:'):
        in_libs = False
    if in_libs:
        r = re.match(r'^\s*-\s*\{id:\s*(\w+),\s*addr:\s*(0x[0-9a-fA-F]+),\s*end:\s*(0x[0-9a-fA-F]+)', line)
        if r:
            ranges[r.group(1)] = (int(r.group(2), 16), int(r.group(3), 16))

hooked_libs = ('libspu', 'libetc', 'libcd', 'libcard')
hle_h = (Path(__file__).resolve().parent / 'hle' / 'hle.h').read_text()
explicit = set(re.findall(r'X\((\w+)\)', hle_h))
names = []
seen = set()
for addr, size, name, asm in yamlfuncs.module_functions(main):
    in_range = any(ranges[l][0] <= addr < ranges[l][1] for l in hooked_libs if l in ranges)
    if (in_range or name in explicit) and name not in seen:
        seen.add(name)
        names.append(name)
for n in sorted(explicit - seen):        # explicit names living in other modules' yaml (none today) or aliases
    names.append(n)

lines = ['/* generated by gen_hle.py */', '#include "hle/hle.h"', 'extern hle_t g_hle_native;']
for n in names:
    lines.append(f'unsigned native_{n}(unsigned a, unsigned b, unsigned c, unsigned d) {{ return hle_call(&g_hle_native, "{n}", a, b, c, d); }}')
lines.append('const char* const g_hle_names[] = {')
for n in names:
    lines.append(f'    "{n}",')
lines.append('    0\n};')
lines.append(f'const int g_hle_name_count = {len(names)};')
# code overlays: the disc position of every module other than the main executable (a CD read that starts there loads code)
modules = []
for y in sorted((repo / 'target').glob('*.yaml')):
    hdr = {}
    for line in y.read_text().splitlines()[:30]:
        m = re.match(r'^(file|lba|size|load):\s*(\S+)', line)
        if m:
            hdr[m.group(1)] = m.group(2)
    if y.name != 'main.yaml' and {'file', 'lba', 'size', 'load'} <= hdr.keys():
        modules.append((hdr['file'], int(hdr['lba']), (int(hdr['size']) + 2047) // 2048, int(hdr['load'], 16), y.stem))
lines.append('struct module_lba { const char* file; unsigned lba, sectors, load; const char* name; };')
lines.append('const struct module_lba g_module_lbas[] = {')
for f, lba, secs, load, stem in modules:
    lines.append(f'    {{ "{f}", {lba}u, {secs}u, 0x{load:08x}u, "{stem}" }},')
lines.append('    { 0, 0, 0, 0, 0 }\n};')
lines.append(f'const int g_module_lba_count = {len(modules)};')
out.write_bytes(('\n'.join(lines) + '\n').encode())
(out.with_name('hle_natives.txt')).write_bytes(('\n'.join('native_' + n for n in names) + '\n').encode())
print(f'{len(names)} SDK functions taken over by the HLE -> {out}')
