"""gen_stubs.py REPO OUT.c [module.yaml ...]  -- a table {PS1 address, native function} for every decompiled function of the
given modules. The natives are WEAK references: a function that is not linked into the program has a null pointer and gets no
trampoline. The runtime writes an x86 `jmp` at each PS1 address so that function pointers stored in the game's data (formula
tables, callbacks) -- which hold PS1 addresses -- land on the native code."""
import re, sys
from pathlib import Path
repo, out = Path(sys.argv[1]), sys.argv[2]
mods = sys.argv[3:] or ['main.yaml', 'battle.yaml']
row = re.compile(r'^\s*-\s*\{addr:\s*(0x[0-9a-fA-F]+),\s*size:\s*(\d+),\s*name:\s*([A-Za-z_]\w*)')
seen, entries = set(), []
for m in mods:
    for l in (repo / 'target' / m).read_text().splitlines():
        r = row.match(l)
        if r and r.group(3) not in seen:
            seen.add(r.group(3))
            entries.append((int(r.group(1), 16), int(r.group(2)), r.group(3)))
lines = ['/* generated by gen_stubs.py */',
         'struct native_stub { unsigned int ps1_addr; unsigned int size; void* native; };']
for _, _, n in entries:
    lines.append(f'extern char {n}[] __attribute__((weak));')
lines.append('const struct native_stub g_native_stubs[] = {')
for a, s, n in entries:
    lines.append(f'    {{ 0x{a:08x}u, {s}u, (void*){n} }},')
lines.append('    { 0, 0, 0 }')
lines.append('};')
lines.append(f'const int g_native_stub_count = {len(entries)};')
Path(out).write_text('\n'.join(lines) + '\n')
print(f'{len(entries)} function stubs -> {out}')
