"""gen_modinfo.py REPO OUT.c module.yaml ...

module_files.c for the function fuzz:
  * g_module_files: the overlay images (every module except the first, which is the main executable) that the harness loads into RAM
    next to SCUS_942.21, at their load addresses -- the original machine code the interpreter runs;
  * g_foreign_entries: the entry addresses of the functions of modules that the chosen ones LINK to (`links: [...]` in the yaml header)
    but that are not part of this build (e.g. WORLD calls BATTLE-hosted functions). In the original a call there lands in whatever
    overlay is resident, so the harness skips a trial that reaches one; natively such references are stubs.
Prints `dirs: src/main src/battle ...` (the source directories of the modules) for the caller."""
import re, sys
from pathlib import Path

repo, out = Path(sys.argv[1]), Path(sys.argv[2])
mods = sys.argv[3:]
sys.path.insert(0, str(Path(__file__).resolve().parent))
import yamlfuncs

lines = ['/* generated by gen_modinfo.py */',
         'struct module_file { const char* path; unsigned int addr; };',
         'const struct module_file g_module_files[] = {']
dirs = []
links = []
mine = set()
mine_entries = set()
for i, m in enumerate(mods):
    hdr = {}
    for line in (repo / 'target' / m).read_text().splitlines()[:40]:
        r = re.match(r'^(file|load|source_dir|links):\s*(.*\S)', line)
        if r:
            hdr[r.group(1)] = r.group(2)
    if hdr.get('source_dir') and hdr['source_dir'] not in dirs:
        dirs.append(hdr['source_dir'])
    if i > 0:
        lines.append(f'    {{ "/disc/{hdr["file"]}", {hdr["load"]}u }},')
    for l in re.findall(r'\w+', hdr.get('links', '')):
        if l not in links:
            links.append(l)
    mine.add(Path(m).stem)
    for addr, size, name, asm in yamlfuncs.module_functions(repo / 'target' / m):
        mine_entries.add(addr)
lines.append('    { 0, 0 }\n};')
foreign = []
for l in links:
    if l in mine or not (repo / 'target' / f'{l}.yaml').exists():
        continue
    for addr, size, name, asm in yamlfuncs.module_functions(repo / 'target' / f'{l}.yaml'):
        if addr not in mine_entries and addr not in foreign:
            foreign.append(addr)
lines.append('const unsigned int g_foreign_entries[] = {')
for a in sorted(foreign):
    lines.append(f'    0x{a:08x}u,')
lines.append('    0\n};')
out.write_bytes(('\n'.join(lines) + '\n').encode())
print('dirs: ' + ' '.join(dirs))
print(f'foreign entries: {len(foreign)}')
print('links: ' + ' '.join(l for l in links if l not in mine and (repo / 'target' / f'{l}.yaml').exists()))
