"""gen_modules.py REPO OUT.c [--native-prefix=native_] [module.yaml ...]

The module registry of the whole-program lockstep: one row per code module (the main executable first, then the overlays), each with
its disc position (a CD read that starts inside it loads its code), its load address and the table of its functions:

    struct mfn    { unsigned addr, size; void* native; const char* name; int arity; }   -- native = weak reference to <prefix><name> (0 when not linked); arity = parameter count (-1 unknown)
    struct module { const char* name; const char* file; unsigned lba, sectors, load; const struct mfn* fns; int nfns; }

The runtime writes an x86 `jmp` at each PS1 function address of the modules that are loaded (see lockstep.c). Handwritten routines
(yamlfuncs.py) are included; names that appear in more than one yaml FILE are kept in the first file only (their PS1 address is the
one the linker script binds; the documents of one multi-document file may repeat a name, each copy keeps its row). A multi-document yaml (event.yaml: 11 overlays, effect.yaml: 110) contributes one module per document."""
import re, sys
from pathlib import Path

args = sys.argv[1:]
prefix = ''
for a in list(args):
    if a.startswith('--native-prefix='):
        prefix = a.split('=', 1)[1]
        args.remove(a)
repo, out = Path(args[0]), Path(args[1])
mods = args[2:] or ['main.yaml', 'battle.yaml']
sys.path.insert(0, str(Path(__file__).resolve().parent))
import yamlfuncs

# parameter count of every function, from its reconstructed source or a header declaration (-1: unknown / variadic); the lockstep replay compares that many
# argument registers at every call
def _strip(t):
    return re.sub(r'//[^\n]*', ' ', re.sub(r'/\*.*?\*/', ' ', t, flags=re.S))
_src = {}
for _p in (repo / 'src').rglob('*.c'):
    _src.setdefault(_p.stem, []).append(_p)
_hdrs = None
def _count(params):
    params = params.strip()
    if params in ('', 'void'):
        return 0
    if '...' in params:
        return -1
    depth, n = 0, 1
    for ch in params:
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        elif ch == ',' and depth == 0:
            n += 1
    return n
def arity(name):
    global _hdrs
    for p in _src.get(name, []):
        t = _strip(p.read_text(errors='replace'))
        m = re.search(r'(?m)^[A-Za-z_][\w \t\*]*?\b' + re.escape(name) + r'\s*\(([^{;]*)\)\s*\{', t)
        if m:
            return _count(m.group(1))
    if _hdrs is None:
        _hdrs = [_strip(h.read_text(errors='replace')) for h in (repo / 'include').rglob('*.h')]
    for t in _hdrs:
        m = re.search(r'\b' + re.escape(name) + r'\s*\(([^;{]*)\)\s*;', t)
        if m:
            return _count(m.group(1))
    return -1

seen = {}                                                        # name -> the yaml FILE that defined it first
modules = []
for m in mods:
    y = repo / 'target' / m
    for stem, hdr, lines in yamlfuncs.modules(y):                 # one module per document (event.yaml / effect.yaml hold one overlay file each)
        fns = []
        for addr, size, name, asm in yamlfuncs.parse_lines(lines):
            if seen.get(name, m) != m:                            # defined by an earlier yaml file: that module's PS1 address is the one bound
                continue
            seen[name] = m                                        # (the documents of one file may repeat a name at other addresses: each copy gets its own row)
            fns.append((addr, size, name, arity(name)))
        modules.append((stem, hdr, fns))

lines = ['/* generated by gen_modules.py */',
         'struct mfn { unsigned int addr; unsigned int size; void* native; const char* name; int arity; };',
         'struct module { const char* name; const char* file; unsigned int lba, sectors, load; const struct mfn* fns; int nfns; };']
for _, _, fns in modules:
    for _, _, n, _ in fns:
        lines.append(f'extern char {prefix}{n}[] __attribute__((weak));')
for stem, hdr, fns in modules:
    lines.append(f'static const struct mfn g_fns_{stem}[] = {{')
    for a, s, n, ar in fns:
        lines.append(f'    {{ 0x{a:08x}u, {s}u, (void*){prefix}{n}, "{n}", {ar} }},')
    lines.append('    { 0, 0, 0, 0, 0 }\n};')
lines.append('const struct module g_modules[] = {')
for stem, hdr, fns in modules:
    h = {k: (v.split() or ['?'])[0] for k, v in hdr.items()}      # the first token: a trailing comment is not part of the value
    secs = (int(h.get('size', '0')) + 2047) // 2048
    lines.append(f'    {{ "{stem}", "{h.get("file", "?")}", {int(h.get("lba", "0"))}u, {secs}u, {h.get("load", "0")}u, g_fns_{stem}, {len(fns)} }},')
lines.append('    { 0, 0, 0, 0, 0, 0, 0 }\n};')
lines.append(f'const int g_module_count = {len(modules)};')
out.write_bytes(('\n'.join(lines) + '\n').encode())
listing = [m[0] + ':' + str(len(m[2])) for m in modules]
if len(listing) > 12:
    listing = listing[:12] + [f'... {len(modules) - 12} more']
print(f'{len(modules)} modules ({", ".join(listing)}) -> {out}')
