"""gen_hle.py REPO OUT.c [module.yaml ...]

Generates OUT.c for the lockstep runtime: for every function the HLE takes over (see hle/hle.h) a native entry point
`native_<name>(a, b, c, d)` that forwards to hle_call() on the native machine's hle_t, and per module the list of those names (the
interpreter side intercepts the original entry addresses of a module while that module is loaded).

Taken over, per module: every function in its libspu / libetc / libcd / libcard / libpress address ranges (yaml `libraries:`), plus
HLE_EXPLICIT_NAMES (BIOS event API, hardware-facing libgpu entry points) and HLE_SKIP_NAMES (render-only hand-written routines) that the
module defines. The names are written to hle_natives.txt next to OUT.c: objects that define one of them are not linked natively."""
import re, sys
from pathlib import Path

repo, out = Path(sys.argv[1]), Path(sys.argv[2])
mods = sys.argv[3:] or ['main.yaml']
sys.path.insert(0, str(Path(__file__).resolve().parent))
import yamlfuncs

hle_h = (Path(__file__).resolve().parent / 'hle' / 'hle.h').read_text()
def macro_names(macro):
    m = re.search(r'#define ' + macro + r'\(X\)(.*?)(?:\n\n|\n/\*|\Z)', hle_h, re.S)
    return set(re.findall(r'X\((\w+)\)', m.group(1))) if m else set()
explicit = macro_names('HLE_EXPLICIT_NAMES')
skip = macro_names('HLE_SKIP_NAMES')
hooked_libs = ('libspu', 'libetc', 'libcd', 'libcard', 'libpress')
# libraries that are replaced natively (software GTE): the HLE calls the ORIGINAL code makes from inside them (critical sections, FlushCache ...) have no native counterpart, so the
# interpreter side does not log them (the calls a natively compiled SDK makes are logged on both sides)
untraced_libs = ('libgte',)
untraced = []

def strip(t):
    return re.sub(r'//[^\n]*', ' ', re.sub(r'/\*.*?\*/', ' ', t, flags=re.S))
src_by_name = {}
for p in (repo / 'src').rglob('*.c'):
    src_by_name.setdefault(p.stem, []).append(p)
_hdrs = None
def arity(name):
    """number of parameters of an SDK function, from its reconstructed source or a header declaration (4 = unknown: compare all)"""
    global _hdrs
    for p in src_by_name.get(name, []):
        t = strip(p.read_text(errors='replace'))
        m = re.search(r'(?m)^[A-Za-z_][\w \t\*]*?\b' + re.escape(name) + r'\s*\(([^)]*)\)\s*\{', t)
        if m:
            a = m.group(1).strip()
            return 0 if a in ('', 'void') else min(4, len([x for x in a.split(',') if x.strip()]))
    if _hdrs is None:
        _hdrs = [strip(h.read_text(errors='replace')) for h in (repo / 'include').rglob('*.h')]
    for t in _hdrs:
        m = re.search(r'\b' + re.escape(name) + r'\s*\(([^)]*)\)\s*;', t)
        if m:
            a = m.group(1).strip()
            return 0 if a in ('', 'void') else min(4, len([x for x in a.split(',') if x.strip()]))
    return 4

per_module = []                                  # (stem, [names])
all_names = []
for m in mods:
    y = repo / 'target' / m
    ranges = []
    in_libs = False
    for line in y.read_text().splitlines():
        if line.startswith('libraries:'):
            in_libs = True
            continue
        if line.startswith('functions:') or line.startswith('---'):
            in_libs = False
        if in_libs:
            r = re.match(r'^\s*-\s*\{id:\s*(\w+),\s*addr:\s*(0x[0-9a-fA-F]+),\s*end:\s*(0x[0-9a-fA-F]+)', line)
            if r and r.group(1) in hooked_libs:
                ranges.append((int(r.group(2), 16), int(r.group(3), 16)))
            if r and r.group(1) in untraced_libs:
                untraced.append((int(r.group(2), 16), int(r.group(3), 16)))
    names = []
    for addr, size, name, asm in yamlfuncs.module_functions(y):
        if (any(lo <= addr < hi for lo, hi in ranges) or name in explicit or name in skip) and name not in names:
            names.append(name)
    per_module.append((y.stem, names))
    for n in names:
        if n not in all_names:
            all_names.append(n)

arities = {n: arity(n) for n in all_names}
lines = ['/* generated by gen_hle.py */', '#include "hle/hle.h"', 'extern hle_t g_hle_native;']
for n in all_names:
    lines.append(f'unsigned native_{n}(unsigned a, unsigned b, unsigned c, unsigned d) {{ return hle_call(&g_hle_native, "{n}", {arities[n]}, a, b, c, d); }}')
for stem, names in per_module:
    lines.append(f'static const char* const g_hle_names_{stem}[] = {{')
    for n in names:
        lines.append(f'    "{n}",')
    lines.append('    0\n};')
    lines.append(f'static const unsigned char g_hle_arity_{stem}[] = {{ ' + ''.join(str(arities[n]) + ', ' for n in names) + '0 };')
lines.append('struct hle_module_names { const char* module; const char* const* names; int count; const unsigned char* arity; };')
lines.append('const struct hle_module_names g_hle_module_names[] = {')
for stem, names in per_module:
    lines.append(f'    {{ "{stem}", g_hle_names_{stem}, {len(names)}, g_hle_arity_{stem} }},')
lines.append('    { 0, 0, 0, 0 }\n};')
lines.append(f'const int g_hle_module_name_count = {len(per_module)};')
lines.append('const unsigned g_hle_untraced[] = { ' + ''.join(f'0x{lo:08x}u, 0x{hi:08x}u, ' for lo, hi in untraced) + '0, 0 };')
out.write_bytes(('\n'.join(lines) + '\n').encode())
(out.with_name('hle_natives.txt')).write_bytes(('\n'.join('native_' + n for n in all_names) + '\n').encode())
print(f'{len(all_names)} functions taken over by the HLE ({", ".join(s + ":" + str(len(n)) for s, n in per_module)}) -> {out}')
