"""gen_modules.py REPO OUT.c [--native-prefix=native_] [module.yaml ...]

The module registry of the whole-program lockstep: one row per code module (the main executable first, then the overlays), each with
its disc position (a CD read that starts inside it loads its code), its load address and the table of its functions:

    struct mfn    { unsigned addr, size; void* native; const char* name; }   -- native = weak reference to <prefix><name> (0 when not linked)
    struct module { const char* name; const char* file; unsigned lba, sectors, load; const struct mfn* fns; int nfns; }

The runtime writes an x86 `jmp` at each PS1 function address of the modules that are loaded (see lockstep.c). Handwritten routines
(yamlfuncs.py) are included; names that appear in more than one module are kept in the first module only (their PS1 address is the
one the linker script binds). A multi-document yaml (event.yaml: 11 overlays, effect.yaml: 110) contributes one module per document."""
import re, sys
from pathlib import Path

args = sys.argv[1:]
prefix = ''
for a in list(args):
    if a.startswith('--native-prefix='):
        prefix = a.split('=', 1)[1]
        args.remove(a)
repo, out = Path(args[0]), Path(args[1])
mods = args[2:] or ['main.yaml', 'battle.yaml']
sys.path.insert(0, str(Path(__file__).resolve().parent))
import yamlfuncs

seen = set()
modules = []
for m in mods:
    y = repo / 'target' / m
    for stem, hdr, lines in yamlfuncs.modules(y):                 # one module per document (event.yaml / effect.yaml hold one overlay file each)
        fns = []
        for addr, size, name, asm in yamlfuncs.parse_lines(lines):
            if name in seen:
                continue
            seen.add(name)
            fns.append((addr, size, name))
        modules.append((stem, hdr, fns))

lines = ['/* generated by gen_modules.py */',
         'struct mfn { unsigned int addr; unsigned int size; void* native; const char* name; };',
         'struct module { const char* name; const char* file; unsigned int lba, sectors, load; const struct mfn* fns; int nfns; };']
for _, _, fns in modules:
    for _, _, n in fns:
        lines.append(f'extern char {prefix}{n}[] __attribute__((weak));')
for stem, hdr, fns in modules:
    lines.append(f'static const struct mfn g_fns_{stem}[] = {{')
    for a, s, n in fns:
        lines.append(f'    {{ 0x{a:08x}u, {s}u, (void*){prefix}{n}, "{n}" }},')
    lines.append('    { 0, 0, 0, 0 }\n};')
lines.append('const struct module g_modules[] = {')
for stem, hdr, fns in modules:
    h = {k: (v.split() or ['?'])[0] for k, v in hdr.items()}      # the first token: a trailing comment is not part of the value
    secs = (int(h.get('size', '0')) + 2047) // 2048
    lines.append(f'    {{ "{stem}", "{h.get("file", "?")}", {int(h.get("lba", "0"))}u, {secs}u, {h.get("load", "0")}u, g_fns_{stem}, {len(fns)} }},')
lines.append('    { 0, 0, 0, 0, 0, 0, 0 }\n};')
lines.append(f'const int g_module_count = {len(modules)};')
out.write_bytes(('\n'.join(lines) + '\n').encode())
print(f'{len(modules)} modules ({", ".join(m[0] + ":" + str(len(m[2])) for m in modules)}) -> {out}')
