/* Whole-program lockstep: the ORIGINAL game (R3000 interpreter) and the NATIVE build of the same game boot side by side from the
 * start of main(), each on its own RAM image with the same HLE SDK layer (hle/), and their RAM is compared at every VSync.
 *
 * Machine A (original): the interpreter runs __SN_ENTRY_POINT up to main(), then continues from there.
 * Machine B (native):   at main() the interpreter's RAM (data ranges) is copied into the native RAM image and the native game's
 *                       main() runs on its own coroutine stack; every native VSync(0) switches back here.
 * Then, per frame: run B to its next sync point, run A to its next sync point, compare all data RAM (see harness_fuzz.c for the
 * ranges and the words that are legitimately different). A sync point is a VSync(0) or a CD read that loads a code overlay (the
 * native side only knows the modules it was built with, so the comparison stops there). The first mismatching frame is reported
 * with labelled words.
 * Freestanding -m32; build/run with lockstep.ps1. */
#include "gte.h"
#include "r3000/r3000.h"
#include "hle/hle.h"
#include "thread_window.h"
#include "dump_around.h"                                               /* generated by lockstep.ps1 (-DumpAround): maybe empty */

#ifndef MAX_FRAMES
#define MAX_FRAMES 60
#endif
#ifndef LOG_LIMIT
#define LOG_LIMIT 0
#endif
#ifndef STEP_BUDGET
#define STEP_BUDGET 400000000ull
#endif
#ifndef SHOW_DIFFS
#define SHOW_DIFFS 40
#endif

/* ---------------------------------------------------------------------------------------- freestanding I/O */
static long sys3(long n, long a, long b, long c) {
    long r;
    __asm__ volatile("int $0x80" : "=a"(r) : "0"(n), "b"(a), "c"(b), "d"(c) : "memory");
    return r;
}
static long sys4(long n, long a, long b, long c, long d) {
    long r;
    __asm__ volatile("int $0x80" : "=a"(r) : "0"(n), "b"(a), "c"(b), "d"(c), "S"(d) : "memory");
    return r;
}
static void out(const char* s) { long n = 0; while (s[n]) n++; sys3(4, 1, (long)s, n); }
static void outnum(long v) {
    char buf[24]; int i = 23, neg = v < 0; buf[23] = 0;
    if (neg) v = -v;
    do { buf[--i] = '0' + v % 10; v /= 10; } while (v);
    if (neg) buf[--i] = '-';
    out(buf + i);
}
static void outhex(unsigned v) {
    char buf[11]; int i;
    for (i = 0; i < 8; i++) buf[i] = "0123456789abcdef"[(v >> (4 * (7 - i))) & 15];
    buf[8] = 0; out(buf);
}
struct old_mmap_args { long addr, len, prot, flags, fd, off; };
static int map_fixed(unsigned addr, unsigned len) { struct old_mmap_args a; a.addr = (long)addr; a.len = (long)len; a.prot = 7; a.flags = 0x32; a.fd = -1; a.off = 0; return sys3(90, (long)&a, 0, 0) == (long)addr; }
static long load_file(const char* path, unsigned char* dst) {
    long fd = sys3(5, (long)path, 0, 0), total = 0, n;
    if (fd < 0) return -1;
    while ((n = sys3(3, fd, (long)(dst + total), 1 << 20)) > 0) total += n;
    sys3(6, fd, 0, 0);
    return total;
}
static int streq(const char* a, const char* b) { while (*a && *a == *b) { a++; b++; } return *a == *b; }

extern unsigned g_bios_rand_seed;                                            /* bios_rt.c: the native BIOS services (rand, memset, strlen, ...) */

/* ------------------------------------------------------------------------------------------------- tables */
struct mfn { unsigned int addr; unsigned int size; void* native; const char* name; int arity; };  /* gen_modules.py: one row per function of a module */
struct module { const char* name; const char* file; unsigned int lba, sectors, load; const struct mfn* fns; int nfns; };
extern const struct module g_modules[];                                     /* [0] = the main executable, then the overlays */
extern const int g_module_count;
struct sym { unsigned int addr; const char* name; };
extern const struct sym g_syms[];
extern const int g_sym_count;
struct hle_module_names { const char* module; const char* const* names; int count; const unsigned char* arity; };      /* gen_hle.py: the functions the HLE takes over, per module */
extern const struct hle_module_names g_hle_module_names[];
extern const int g_hle_module_name_count;
extern unsigned g_stub_calls;                                               /* generated with the stubs of the yaml functions that have no native definition */
extern const char* const g_stub_names[];
extern unsigned g_stub_hits[];
extern const int g_stub_count;

static int g_active[8], g_nactive;                                          /* the code overlays whose functions are installed (they occupy disjoint address ranges) */
static unsigned addr_in(int mod, const char* name) {
    int i;
    for (i = 0; i < g_modules[mod].nfns; i++) if (streq(g_modules[mod].fns[i].name, name)) return g_modules[mod].fns[i].addr;
    return 0;
}
static unsigned addr_of(const char* name) { return addr_in(0, name); }     /* main-executable functions (the SDK entry points and main) */
static const struct mfn* fn_at(unsigned pc, int module) {
    int i;
    for (i = 0; i < g_modules[module].nfns; i++) { const struct mfn* f = &g_modules[module].fns[i]; if (pc >= f->addr && pc < f->addr + f->size) return f; }
    return 0;
}
static void func_at(unsigned pc) {
    const struct mfn* f = fn_at(pc, 0);
    int i;
    for (i = 0; !f && i < g_nactive; i++) f = fn_at(pc, g_active[i]);
    if (f) { out(f->name); out("+0x"); outhex(pc - f->addr); return; }
    outhex(pc);
}
static void label(unsigned a) {
    int lo = 0, hi = g_sym_count, i;
    while (lo < hi) { int mid = (lo + hi) / 2; if (g_syms[mid].addr <= a) lo = mid + 1; else hi = mid; }
    i = lo - 1;
    if (i >= 0 && a - g_syms[i].addr < 0x4000) { out(g_syms[i].name); out("+0x"); outhex(a - g_syms[i].addr); return; }
    outhex(a);
}

/* ------------------------------------------------------------------------------- RAM ranges and trampolines */
static unsigned char interp_ram[0x200000];
static r3k_t cpu;
static unsigned data_lo[6000], data_hi[6000];
static int ndata;

/* Data ranges = everything below the stack area that is not the code of a loaded module (the main executable and the active overlay). */
static void build_ranges(void) {
    static unsigned idx[8192];
    int i, j, n = 0, m;
    unsigned cursor = 0x80000000u;
    static const struct mfn* tab[8192];                                     /* static: an auto-initialised local array would call memset before the trampolines exist */
    for (m = 0; m <= g_nactive; m++) {
        int mod = m == 0 ? 0 : g_active[m - 1];
        for (i = 0; i < g_modules[mod].nfns && n < 8192; i++) tab[n++] = &g_modules[mod].fns[i];
    }
    for (i = 0; i < n; i++) idx[i] = (unsigned)i;
    for (i = 1; i < n; i++) { unsigned v = idx[i]; for (j = i - 1; j >= 0 && tab[idx[j]]->addr > tab[v]->addr; j--) idx[j + 1] = idx[j]; idx[j + 1] = v; }
    ndata = 0;
    for (i = 0; i < n; i++) {
        const struct mfn* f = tab[idx[i]];
        if (f->addr >= 0x801f0000u) continue;
        if (f->addr > cursor) { data_lo[ndata] = cursor; data_hi[ndata] = f->addr; ndata++; }
        if (f->addr + f->size > cursor) cursor = f->addr + f->size;
    }
    if (cursor < 0x801f0000u) { data_lo[ndata] = cursor; data_hi[ndata] = 0x801f0000u; ndata++; }
}
/* Function coverage: every trampoline jumps to a 16-byte thunk `inc dword [counter]; jmp native` (every call in the PS1-address scheme goes through the trampoline at the
 * function's PS1 address, so the counters see every call). write_coverage() lists the functions that ran, per module, into /cov/hits.txt when that directory is mounted. */
#define COV_MAX 8192
#define THUNK_BASE 0x0a000000u
#define THUNK_BYTES (16u * COV_MAX)
static unsigned g_cov[COV_MAX];
static unsigned fn_id(int mod, int i) { int m; unsigned id = 0; for (m = 0; m < mod; m++) id += (unsigned)g_modules[m].nfns; return id + (unsigned)i; }
/* the functions whose entry is an observed tick of virtual time (hle.h HLE_TICK_NAMES): the thunk calls ls_native_tick() first; the interpreter side observes the same entries */
struct hle_module_ticks { const char* module; const char* const* names; };
extern const struct hle_module_ticks g_hle_module_ticks[];
static int is_tick_fn(int mod, const char* name) {
    int j, k;
    for (j = 0; g_hle_module_ticks[j].module; j++) {
        if (!streq(g_hle_module_ticks[j].module, g_modules[mod].name)) continue;
        for (k = 0; g_hle_module_ticks[j].names[k]; k++) if (streq(g_hle_module_ticks[j].names[k], name)) return 1;
    }
    return 0;
}
extern void ls_native_tick(void);
static unsigned thunk_target(int mod, int i, unsigned native) {
    unsigned id = fn_id(mod, i);
    unsigned char* t;
    if (id >= COV_MAX) return native;
    t = (unsigned char*)(THUNK_BASE + 16u * id);
    t[0] = 0xff; t[1] = 0x05; *(unsigned*)(t + 2) = (unsigned)&g_cov[id];                 /* incl [g_cov + 4 * id] */
    if (is_tick_fn(mod, g_modules[mod].fns[i].name)) {
        t[6] = 0xe8; *(unsigned*)(t + 7) = (unsigned)ls_native_tick - ((unsigned)t + 11u);   /* call ls_native_tick (arguments and callee-saved registers are untouched) */
        t[11] = 0xe9; *(unsigned*)(t + 12) = native - ((unsigned)t + 16u);                 /* jmp native */
        return (unsigned)t;
    }
    t[6] = 0xe9; *(unsigned*)(t + 7) = native - ((unsigned)t + 11u);                       /* jmp native */
    return (unsigned)t;
}
/* x86 `jmp` trampolines at the PS1 addresses of a module's natively compiled functions; returns how many were installed */
static int install_module(int mod) {
    int i, n = 0;
    for (i = 0; i < g_modules[mod].nfns; i++) {
        const struct mfn* f = &g_modules[mod].fns[i];
        if (f->native && f->size >= 5) {
            unsigned char* p = (unsigned char*)f->addr;
            p[0] = 0xe9; *(unsigned*)(p + 1) = thunk_target(mod, i, (unsigned)f->native) - (f->addr + 5);
            n++;
        }
    }
    return n;
}
static char g_covbuf[1 << 17];
static long g_covlen;
static void cov_str(const char* t) { while (*t && g_covlen < (long)sizeof g_covbuf - 1) g_covbuf[g_covlen++] = *t++; }
static void cov_num(unsigned x) { char d[12]; int q = 11; d[11] = 0; do { d[--q] = (char)('0' + x % 10); x /= 10; } while (x); cov_str(d + q); }
static void cov_flush(long fd) { if (g_covlen) sys3(4, fd, (long)g_covbuf, g_covlen); g_covlen = 0; }
static void write_coverage(void) {
    long fd = sys3(5, (long)"/cov/hits.txt", 0x241, 0x1a4);
    int m, i;
    if (fd < 0) return;
    g_covlen = 0;
    for (m = 0; m < g_module_count; m++) {
        unsigned nat = 0, hit = 0;
        for (i = 0; i < g_modules[m].nfns; i++) { unsigned id = fn_id(m, i); if (g_modules[m].fns[i].native) nat++; if (id < COV_MAX && g_cov[id]) hit++; }
        cov_str("module "); cov_str(g_modules[m].name); cov_str(" total "); cov_num((unsigned)g_modules[m].nfns); cov_str(" native "); cov_num(nat); cov_str(" hit "); cov_num(hit); cov_str("\n");
        for (i = 0; i < g_modules[m].nfns; i++) {
            unsigned id = fn_id(m, i);
            if (id < COV_MAX && g_cov[id]) { cov_str(g_modules[m].fns[i].name); cov_str(" h\n"); }
            if (g_covlen > (long)sizeof g_covbuf - 400) cov_flush(fd);
        }
    }
    cov_flush(fd);
    sys3(6, fd, 0, 0);
}
/* the code bytes of the module that is going away come back from the interpreter's RAM (which holds whatever the game put there) */
static void uninstall_module(int mod);
static unsigned char interp_ram_bytes(unsigned a);
static void uninstall_module(int mod) {
    int i, k;
    for (i = 0; i < g_modules[mod].nfns; i++) {
        const struct mfn* f = &g_modules[mod].fns[i];
        if (f->native && f->size >= 5) for (k = 0; k < 5; k++) ((unsigned char*)f->addr)[k] = interp_ram_bytes(f->addr + (unsigned)k);
    }
}
/* words that legitimately differ: the retail thread switch saves registers into the thread records, the native scheduler keeps them
 * outside RAM; battle_thread_call_on_main_stack and the C runtime keep a saved $ra in RAM */
extern char g_battle_thread_contexts[];
extern char g_world_thread_contexts[];
static int module_active(const char* name) {
    int i;
    for (i = 0; i < g_nactive; i++) if (streq(g_modules[g_active[i]].name, name)) return 1;
    return 0;
}
static int ignored_word(unsigned a) {
    unsigned base = (unsigned)g_battle_thread_contexts, wbase = (unsigned)g_world_thread_contexts;
    if (a < 0x8000f800u) return 1;                             /* BIOS/kernel area: exception-vector patches by the SDK's GTE/card init (the interpreter fakes the kernel tables) */
    /* a record is 0x400 bytes: header (parameters, saved registers 0x10..0x47, task words 0x50..0x6b) and the thread's own stack (0x6c..0x3ff):
     * the retail code spills registers and locals onto that stack, the native thread keeps them on its private x86 stack */
    if (a >= base && a < base + 16 * 0x400) { unsigned off = (a - base) & 0x3ff; if ((off >= 0x10 && off < 0x48) || off >= 0x6c) return 1; }
    if (a >= wbase && a < wbase + 17 * 0x400) { unsigned off = (a - wbase) & 0x3ff; if ((off >= 0x10 && off < 0x48) || off >= 0x6c) return 1; }
    switch (a) {
    case 0x80028ae4u:                                          /* g_psyq_crt_constructors_ran: set by __main, which the native main() does not call */
    case 0x8002b8a8u: case 0x8002bbd8u: case 0x800329bcu: case 0x800329c0u: case 0x800329d0u: case 0x800329e0u:   /* g_psyq_*_saved_ra: return addresses saved by hand-written SDK code */
    case 0x8014cf5cu: case 0x8010042cu:                        /* battle_ / world_thread_call_on_main_stack's saved $ra */
    case 0x80010ba8u:                                          /* battle_bin_entrypoint: a nop sled in retail, a native `ret` (see _start) */
        return 1;
    }
    return 0;
}
/* Stack addresses are machine-specific: the two machines' frames differ in layout (x86 vs MIPS), and a thread's private stack is a 0x400-byte part of its RAM record in
 * the original but lives in the thread-stack window natively. A word that holds such an address (a pointer, or a GPU ordering-table tag: packet length in the top byte, 24-bit
 * link) is "equal" when both machines' values point into the same stack: class 1 = the main stack, 2 + s = battle thread s, 32 + s = world thread s. */
static int stack_class(unsigned v, int native) {
    if (v >= 0x801f0000u && v < 0x80200000u) return 1;
    if (native && v >= MAIN_STACK_WINDOW && v < MAIN_STACK_WINDOW + MAIN_STACK_BYTES) return 1;
    if (native) {
        if (v >= THREAD_STACK_WINDOW && v < THREAD_STACK_WINDOW + 16u * THREAD_STACK_BYTES) return 2 + (int)((v - THREAD_STACK_WINDOW) / THREAD_STACK_BYTES);
        if (v >= THREAD_STACK_WINDOW + THREAD_STACK_WORLD_OFFSET && v < THREAD_STACK_WINDOW + THREAD_STACK_WORLD_OFFSET + 17u * THREAD_STACK_BYTES)
            return 32 + (int)((v - THREAD_STACK_WINDOW - THREAD_STACK_WORLD_OFFSET) / THREAD_STACK_BYTES);
    } else {
        unsigned base = (unsigned)g_battle_thread_contexts, wbase = (unsigned)g_world_thread_contexts;
        if (v >= base && v < base + 16u * 0x400u) return 2 + (int)((v - base) / 0x400u);
        if (v >= wbase && v < wbase + 17u * 0x400u) return 32 + (int)((v - wbase) / 0x400u);
    }
    return 0;
}
static int stackish_equal(unsigned x, unsigned y) {                         /* x: the native machine's word, y: the original's */
    int c = stack_class(x, 1);
    if (c && c == stack_class(y, 0)) return 1;
    if ((x >> 24) == (y >> 24)) { c = stack_class(0x80000000u | (x & 0xffffffu), 1); if (c && c == stack_class(0x80000000u | (y & 0xffffffu), 0)) return 1; }
    return 0;
}
static void copy_data_interp_to_native(void) {
    int i;
    for (i = 0; i < ndata; i++) {
        unsigned n = (data_hi[i] - data_lo[i]) / 4;
        const void* s = interp_ram + (data_lo[i] & 0x1fffff); void* d = (void*)data_lo[i];
        __asm__ volatile("rep movsl" : "+D"(d), "+S"(s), "+c"(n) : : "memory");
    }
}
static int compare_ram(int show) {
    int r, diffs = 0;
    unsigned a;
    for (r = 0; r < ndata; r++)
        for (a = data_lo[r]; a < data_hi[r]; a += 4) {
            unsigned x = *(unsigned*)a, y = *(unsigned*)(interp_ram + (a & 0x1fffff));
            if (x != y && !stackish_equal(x, y) && !ignored_word(a)) {
                if (show && diffs < show) { out("    "); label(a); out("  native "); outhex(x); out("  original "); outhex(y); out("\n"); }
                diffs++;
            }
        }
    return diffs;
}
static unsigned char interp_ram_bytes(unsigned a) { return interp_ram[a & 0x1fffff]; }
/* The first 8 words of the scratchpad are not compared: the retail 64-bit mul/div and cross-product routines (battle_mul_div_s64, battle_fixed_cross_product_q12
 * and their world twins) park their callee-saved registers s0-s7 there and leave them behind; the native versions have no such registers to store. */
#define SCRATCH_FIRST_COMPARED 8
static int compare_scratch(void) {
    int i, diffs = 0;
    for (i = 0; i < g_nactive; i++) if (streq(g_modules[g_active[i]].name, "wldcore")) return 0;   /* WLDCORE runs its frame code on a stack IN the scratchpad (wldcore_switch_to_stack): the retail spills are not reproduced natively */
    for (i = SCRATCH_FIRST_COMPARED; i < 256; i++) if (((unsigned*)0x1f800000u)[i] != ((unsigned*)cpu.scratch)[i]) diffs++;
    return diffs;
}
static void print_scratch_diffs(int max) {
    int i, shown = 0;
    for (i = SCRATCH_FIRST_COMPARED; i < 256 && shown < max; i++) {
        unsigned x = ((unsigned*)0x1f800000u)[i], y = ((unsigned*)cpu.scratch)[i];
        if (x != y) { out("    scratchpad+0x"); outhex((unsigned)i * 4); out("  native "); outhex(x); out("  original "); outhex(y); out("\n"); shown++; }
    }
}

/* -------------------------------------------------------------------------------------------- the disc */
static int g_disc_fd = -1;
static int read_sector(void* ctx, unsigned lba, unsigned char* dst) {
    unsigned char raw[2352];
    long got = 0, n;
    unsigned k;
    (void)ctx;
    if (g_disc_fd < 0) return 0;
    sys3(19, g_disc_fd, (long)(lba * 2352u), 0);
    while (got < 2352 && (n = sys3(3, g_disc_fd, (long)(raw + got), 2352 - got)) > 0) got += n;
    if (got < 2352) return 0;
    for (k = 0; k < 2048; k++) dst[k] = raw[24 + k];
    return 1;
}
static int module_at(unsigned lba) {                                        /* the overlay whose file starts at or contains this sector, else -1 */
    int i;
    for (i = 1; i < g_module_count; i++) if (lba >= g_modules[i].lba && lba < g_modules[i].lba + g_modules[i].sectors) return i;
    return -1;
}
static int is_overlay_lba(void* ctx, unsigned lba) { (void)ctx; return module_at(lba) >= 0; }
/* scripted controller input: {first frame, buttons}; the state holds until the next entry (-Pad in lockstep.ps1) */
static const unsigned g_pad_script[][2] = {
#include "pad_script.h"
    , { 0xffffffffu, 0 } };
/* run-time configuration (the wrapper mounts /run.cfg): "frames N" and "pad FRAME BUTTONS" lines (decimal or 0x..); overrides the compile-time MAX_FRAMES / pad script,
 * so that one linked program serves many runs (soak.ps1) */
static unsigned g_frames = MAX_FRAMES;
static unsigned g_padrt[65536][2];
static int g_npadrt;
/* "pokewhen CADDR CVAL ADDR VAL [REPEAT]": once (every time, with REPEAT = 1), at the start of the first frame in which the (interpreter-side) word at CADDR equals CVAL, VAL is stored into the word at ADDR on BOTH
 * machines -- a cheat that steers the game into states random input rarely reaches (for instance, ending the first battle to get to the world map) */
static struct { unsigned caddr, cval, addr, val, repeat; int done; } g_pokes[64];
static int g_npokes;
static unsigned parse_num(const char** pp) {
    const char* p = *pp;
    unsigned v = 0;
    while (*p == ' ' || *p == '\t') p++;
    if (p[0] == '0' && (p[1] == 'x' || p[1] == 'X')) { p += 2; while ((*p >= '0' && *p <= '9') || (*p >= 'a' && *p <= 'f') || (*p >= 'A' && *p <= 'F')) { v = v * 16 + (unsigned)(*p <= '9' ? *p - '0' : (*p | 32) - 'a' + 10); p++; } }
    else while (*p >= '0' && *p <= '9') { v = v * 10 + (unsigned)(*p - '0'); p++; }
    *pp = p;
    return v;
}
static void load_run_config(void) {
    static char buf[1 << 21];
    long n = load_file("/run.cfg", (unsigned char*)buf);
    const char* p = buf;
    if (n <= 0 || n >= (long)sizeof buf - 1) return;
    buf[n] = 0;
    while (*p) {
        if (p[0] == 'f' && p[1] == 'r') { p += 6; g_frames = parse_num(&p); }                 /* frames N */
        else if (p[0] == 'p' && p[1] == 'o') {                                                 /* pokewhen CADDR CVAL ADDR VAL */
            if (g_npokes < 64) { p += 9; g_pokes[g_npokes].caddr = parse_num(&p); g_pokes[g_npokes].cval = parse_num(&p); g_pokes[g_npokes].addr = parse_num(&p); g_pokes[g_npokes].val = parse_num(&p); g_pokes[g_npokes].repeat = parse_num(&p); g_pokes[g_npokes].done = 0; g_npokes++; }
        }
        else if (p[0] == 'p' && p[1] == 'a') {                                                 /* pad FRAME BUTTONS */
            unsigned f, b;
            p += 3; f = parse_num(&p); b = parse_num(&p);
            if (g_npadrt < 65536) { g_padrt[g_npadrt][0] = f; g_padrt[g_npadrt][1] = b; g_npadrt++; }
        }
        while (*p && *p != '\n') p++;
        if (*p) p++;
    }
}
static unsigned pad_at(unsigned frame) {
    unsigned mask = 0;
    int i;
    if (g_npadrt) { for (i = 0; i < g_npadrt && g_padrt[i][0] <= frame; i++) mask = g_padrt[i][1]; return mask; }
    for (i = 0; g_pad_script[i][0] != 0xffffffffu; i++) if (g_pad_script[i][0] <= frame) mask = g_pad_script[i][1];
    return mask;
}
/* symbols to watch: their (interpreter-side) 32-bit value is printed whenever it changes (-Watch in lockstep.ps1) */
struct watch { unsigned addr; const char* name; };
static const struct watch g_watch[] = {
#include "watch.h"
    { 0, 0 } };
static unsigned g_watch_last[64];
/* memory to dump when the run stops abnormally (-Peek 'symbol:words,...'): {address, words, name} */
struct peek { unsigned addr, words; const char* name; };
static const struct peek g_peek[] = {
#include "peek.h"
    { 0, 0, 0 } };
static void report_watch(int frame) {
    int i;
    for (i = 0; g_watch[i].addr && i < 64; i++) {
        unsigned v = *(unsigned*)(interp_ram + (g_watch[i].addr & 0x1fffff));
        if (v != g_watch_last[i] || frame == 1) { g_watch_last[i] = v; out("  [frame "); outnum(frame); out("] "); out(g_watch[i].name); out(" = 0x"); outhex(v); out("\n"); }
    }
}
static int g_log_budget = LOG_LIMIT;
static void log_call(void* ctx, const char* what, unsigned a0, unsigned a1, unsigned a2) {
    if (g_log_budget > 0) { g_log_budget--; out("    sdk["); out((const char*)ctx); out("] "); out(what); out("("); outhex(a0); out(", "); outhex(a1); out(", "); outhex(a2); out(")\n"); }
}

/* ------------------------------------------------------------------------------ machine A: the interpreter */
static hle_t hle_i;
static unsigned ia_r8(void* c, unsigned a) { (void)c; return interp_ram[a & 0x1fffff]; }
static int ia_valid(void* c, unsigned a) { (void)c; return a >= 0x80000000u && a < 0x80200000u; }
static void ia_w8(void* c, unsigned a, unsigned v) { (void)c; interp_ram[a & 0x1fffff] = (unsigned char)v; }
static void ia_wb(void* c, unsigned a, const unsigned char* s, unsigned n) { unsigned k; (void)c; for (k = 0; k < n; k++) interp_ram[(a + k) & 0x1fffff] = s[k]; }
static unsigned ia_call(void* c, unsigned addr, unsigned a0, unsigned a1) { unsigned args[2]; (void)c; args[0] = a0; args[1] = a1; return r3k_call_nested(&cpu, addr, args, 2, 5000000ull); }
static void ia_frame(void* c) { (void)c; hle_i.stop = 1; }
extern const unsigned g_hle_untraced[];                                      /* gen_hle.py: [lo, hi) address ranges of natively replaced SDK libraries */
static int untraced_caller(unsigned ra) {
    int i;
    for (i = 0; g_hle_untraced[i] || g_hle_untraced[i + 1]; i += 2) if (ra >= g_hle_untraced[i] && ra < g_hle_untraced[i + 1]) return 1;
    return 0;
}
static struct { unsigned addr; const char* name; int module; int arity; } g_hooks[1024];
static int n_hooks;
static unsigned g_main_addr;
static int g_at_main;
static void unhook(unsigned addr);
#ifdef SCENARIO_TITLE
/* Scenario "title": the game loop decides at the top of every iteration whether OPEN plays the opening movie (result != 5) or goes straight
 * to the title menu (5 = "coming back from the world map"). Both machines run main_item_init_new_game_inventory as usual and then the
 * driver stores 5 into g_main_system_frontend_world_result, i.e. steers the game past the FMV (whose streaming hardware is not modelled). */
#define SCENARIO_FN "main_item_init_new_game_inventory"
#define SCENARIO_WORD 0x80045978u
#define SCENARIO_VALUE 5u
static unsigned g_scn_addr;
static int g_scn_active;
#endif
static void interp_tick(r3k_t* c, unsigned addr) { (void)c; (void)addr; hle_tick(&hle_i); }
static int interp_hle(r3k_t* c, unsigned addr) {
    int i, arity = 4;
    const char* n = 0;
    if (addr == g_main_addr) { g_at_main = 1; return 1; }                    /* stop at the entry of main() without running it */
#ifdef SCENARIO_TITLE
    if (addr == g_scn_addr && g_scn_addr) {                                  /* run the original function, then poke */
        unsigned args[4];
        args[0] = c->r[4]; args[1] = c->r[5]; args[2] = c->r[6]; args[3] = c->r[7];
        unhook(addr);
        c->r[2] = r3k_call_nested(c, addr, args, 4, 5000000ull);
        r3k_hle_add(c, addr);
        interp_ram[SCENARIO_WORD & 0x1fffff] = SCENARIO_VALUE; interp_ram[(SCENARIO_WORD & 0x1fffff) + 1] = 0; interp_ram[(SCENARIO_WORD & 0x1fffff) + 2] = 0; interp_ram[(SCENARIO_WORD & 0x1fffff) + 3] = 0;
        return 0;
    }
#endif
    for (i = 0; i < n_hooks; i++) if (g_hooks[i].addr == addr) { n = g_hooks[i].name; arity = g_hooks[i].arity; break; }
    hle_i.no_trace = untraced_caller(c->r[31]);                              /* an HLE call made from inside the (natively replaced) libgte is not compared */
    c->r[2] = hle_call(&hle_i, n ? n : "?", (unsigned)arity, c->r[4], c->r[5], c->r[6], c->r[7]);
    hle_i.no_trace = 0;
    return hle_i.stop;
}
static void unhook(unsigned addr) { unsigned w = (addr & 0x1fffffu) >> 2; cpu.hle_bitmap[w >> 3] &= (unsigned char)~(1u << (w & 7)); }
/* the interpreter intercepts the ORIGINAL entry addresses of the functions the HLE takes over, only while their module is loaded
 * (an overlay's addresses hold other code before and after) */
static void install_tick_hooks(int mod, int on) {
    int j, k;
    for (j = 0; g_hle_module_ticks[j].module; j++) {
        if (!streq(g_hle_module_ticks[j].module, g_modules[mod].name)) continue;
        for (k = 0; g_hle_module_ticks[j].names[k]; k++) {
            unsigned a = addr_in(mod, g_hle_module_ticks[j].names[k]);
            if (a) { if (on) r3k_tick_add(&cpu, a); else r3k_tick_remove(&cpu, a); }
        }
    }
}
static int install_hle_hooks(int mod) {
    int j, i, n = 0;
    install_tick_hooks(mod, 1);
    for (j = 0; j < g_hle_module_name_count; j++) {
        if (!streq(g_hle_module_names[j].module, g_modules[mod].name)) continue;
        for (i = 0; i < g_hle_module_names[j].count && n_hooks < 1024; i++) {
            unsigned a = addr_in(mod, g_hle_module_names[j].names[i]);
            if (a) { g_hooks[n_hooks].addr = a; g_hooks[n_hooks].name = g_hle_module_names[j].names[i]; g_hooks[n_hooks].module = mod; g_hooks[n_hooks].arity = g_hle_module_names[j].arity[i]; n_hooks++; r3k_hle_add(&cpu, a); n++; }
        }
    }
    return n;
}
static void remove_hle_hooks(int mod) {
    int i, k = 0;
    install_tick_hooks(mod, 0);
    for (i = 0; i < n_hooks; i++) {
        if (g_hooks[i].module == mod) unhook(g_hooks[i].addr);
        else g_hooks[k++] = g_hooks[i];
    }
    n_hooks = k;
}

/* --------------------------------------------------------------------------------- machine B: the native game */
hle_t g_hle_native;
extern void native_main(void);
static void* g_driver_esp;
static void* g_game_esp;
static int g_native_dead;
void ls_switch(void** save_esp, void* new_esp);
__asm__(".text\n"
        ".globl ls_switch\n"
        "ls_switch:\n"
        "    movl 4(%esp), %eax\n"
        "    movl 8(%esp), %edx\n"
        "    pushl %ebp\n"
        "    pushl %ebx\n"
        "    pushl %esi\n"
        "    pushl %edi\n"
        "    movl %esp, (%eax)\n"
        "    movl %edx, %esp\n"
        "    popl %edi\n"
        "    popl %esi\n"
        "    popl %ebx\n"
        "    popl %ebp\n"
        "    ret\n");
static void game_entry(void) {
    native_main();
    g_native_dead = 1;
    for (;;) ls_switch(&g_game_esp, g_driver_esp);
}
/* The native threads' stacks (replacements/battle_thread.c, world_thread.c) sit in a window above the 2 MiB of RAM, see thread_window.h */
static unsigned nb_r8(void* c, unsigned a) { (void)c; return *(volatile unsigned char*)a; }
static int nb_valid(void* c, unsigned a) { (void)c; return (a >= 0x80000000u && a < 0x80200000u) || (a >= THREAD_STACK_WINDOW && a < THREAD_STACK_WINDOW + THREAD_STACK_WINDOW_BYTES); }
static void nb_w8(void* c, unsigned a, unsigned v) { (void)c; *(volatile unsigned char*)a = (unsigned char)v; }
static void nb_wb(void* c, unsigned a, const unsigned char* s, unsigned n) { unsigned k; (void)c; for (k = 0; k < n; k++) ((volatile unsigned char*)a)[k] = s[k]; }
void ls_native_tick(void) { hle_tick(&g_hle_native); }
extern unsigned g_ls_ignore_enter;
static unsigned nb_call(void* c, unsigned addr, unsigned a0, unsigned a1) { (void)c; g_ls_ignore_enter = 1; return ((unsigned (*)(unsigned, unsigned))addr)(a0, a1); }
static void nb_frame(void* c) { (void)c; ls_switch(&g_game_esp, g_driver_esp); }
static void start_native_game(void) {
    /* the game's stack lives in the RAM image, at the top like the console's: locals whose addresses go into GPU ordering tables / RAM structures keep valid 24-bit PS1 addresses */
    unsigned* top = (unsigned*)(MAIN_STACK_WINDOW + MAIN_STACK_BYTES);
    top -= 5;
    *--top = (unsigned)game_entry;
    *--top = 0; *--top = 0; *--top = 0; *--top = 0;
    g_game_esp = top;
}

#ifdef SCENARIO_TITLE
extern void native_main_item_init_new_game_inventory(void);
static void scn_wrapper(void) { native_main_item_init_new_game_inventory(); *(volatile unsigned*)SCENARIO_WORD = SCENARIO_VALUE; }
#endif

/* -------------------------------------------------------------------------- crash report for the native side */
static const char* g_where = "before main";
static int g_cur_frame;                                                     /* the frame the driver is running (both machines) */
struct ksigaction { void (*handler)(int, void*, void*); unsigned long flags; void (*restorer)(void); unsigned long long mask; };
/* The retail code sometimes reads (or writes) through a NULL pointer: the console has RAM there (its low kernel area, zero in the oracle), a native process does not. When the
 * container allows it (--cap-add SYS_RAWIO lets a root process map below vm.mmap_min_addr) page zero is mapped zero-filled but kept PROT_NONE: the first touch in a frame faults,
 * the handler records the site (the report at the end lists them: each is a place where a reviewed source patch is needed for a build that cannot map page zero), opens the page
 * and lets the instruction go on; the driver closes it again at the next frame. */
#define NULL_PAGE_BYTES 0x10000u
static int g_null_page_mapped, g_null_page_open;
static unsigned g_null_sites[64];
static int g_n_null_sites;
__asm__(".text\n"
        ".globl ls_sig_restorer\n"
        "ls_sig_restorer:\n"
        "    movl $173, %eax\n"                                      /* rt_sigreturn */
        "    int $0x80\n");
extern void ls_sig_restorer(void);
static void null_page_close(void) { if (g_null_page_mapped && g_null_page_open) { sys3(125, 0, NULL_PAGE_BYTES, 0); g_null_page_open = 0; } }   /* mprotect(PROT_NONE) */
static void report_null_sites(void) {
    int i;
    if (!g_n_null_sites) return;
    out("NULL-PAGE ACCESS by the native game (retail reads console RAM at address 0..0xffff there) at:");
    for (i = 0; i < g_n_null_sites; i++) { out(" @0x"); outhex(g_null_sites[i]); }
    out("\n");
}
static void (*g_crash_context)(void);                                       /* set by the replay: where in the replayed frame the native game was */
static void fault_handler(int sig, void* info, void* uc) {
    unsigned eip = *(unsigned*)((char*)uc + 76), ebp = *(unsigned*)((char*)uc + 44);
    int depth;
    if (sig == 11 && g_null_page_mapped && *(unsigned*)((char*)info + 12) < NULL_PAGE_BYTES) {          /* a touch of the NULL page: note the site, open the page, retry */
        int k, known = 0;
        for (k = 0; k < g_n_null_sites; k++) if (g_null_sites[k] == eip) known = 1;
        if (!known && g_n_null_sites < 64) g_null_sites[g_n_null_sites++] = eip;
        sys3(125, 0, NULL_PAGE_BYTES, 3);                                                              /* mprotect(PROT_READ | PROT_WRITE) */
        g_null_page_open = 1;
        return;
    }
    report_null_sites();
    out(sig == 14 ? "\nNATIVE HANG (no VSync within the watchdog time): signal " : "\nNATIVE CRASH: signal "); outnum(sig); out(" at @0x"); outhex(eip); out(", address 0x"); outhex(*(unsigned*)((char*)info + 12));
    out("; last sync: "); out(g_where); out(", native VSync count "); outnum(g_hle_native.frame_counter); out("; driver frame "); outnum(g_cur_frame); out("\n  backtrace:");
    for (depth = 0; depth < 24 && ebp >= 0x08000000u && ebp < 0xc0000000u && (ebp & 3) == 0; depth++) {
        unsigned ra = ((unsigned*)ebp)[1];
        out(" @0x"); outhex(ra);
        if (((unsigned*)ebp)[0] <= ebp) break;
        ebp = ((unsigned*)ebp)[0];
    }
    out("\n  stack top:");
    {   unsigned sp = *(unsigned*)((char*)uc + 48), q;
        for (q = 0; q < 12 && sp >= 0x08000000u && sp < 0xc0000000u; q++) { out(" @0x"); outhex(((unsigned*)sp)[q]); }
    }
    out("\n");
    if (g_crash_context) g_crash_context();
    write_coverage();
    sys3(1, 3, 0, 0);
}
static void install_fault_handlers(void) {
    struct ksigaction sa;
    sa.handler = fault_handler; sa.flags = 4 | 0x40000000 | 0x04000000; sa.restorer = ls_sig_restorer; sa.mask = 0;      /* SA_SIGINFO | SA_NODEFER | SA_RESTORER */
    sys4(174, 11, (long)&sa, 0, 8); sys4(174, 8, (long)&sa, 0, 8); sys4(174, 7, (long)&sa, 0, 8); sys4(174, 4, (long)&sa, 0, 8); sys4(174, 14, (long)&sa, 0, 8);   /* SIGALRM: the native watchdog */
}

/* ------------------------------------------------------------------------------------------------ replay */
#ifdef REPLAY_FRAME
/* Replay of ONE frame at function granularity: the original runs first and its sequence of function entries (calls into functions of the module
 * tables) is recorded; then the native game runs the same frame and every function it enters is compared LIVE with the recorded sequence. The first
 * difference -- a different callee, or more calls than the original made (a native hang) -- stops the native game on the spot: the function that ran
 * just before it made a different decision. Needs the game compiled with -finstrument-functions (lockstep.ps1 does). */
#define EV_MAX 600000
static unsigned ev_int[EV_MAX], ev_a0[EV_MAX], ev_a1[EV_MAX], ev_ra[EV_MAX];                /* ev_ra: $ra at the call = where the callee returns to (its caller) */
#define EV_SCR_MAX 150000                                                   /* the first 8 words of the scratchpad at each of the original's first calls (the native game is compared with them) */
static unsigned ev_scr[EV_SCR_MAX][8];
static unsigned ev_w[EV_SCR_MAX][4];                                        /* the first 4 -Watch words at each of the original's first calls */
static unsigned g_div_scratch, g_div_scr_native[8], g_div_watch, g_div_w_native;
/* Arguments: at each call the original's argument registers a0-a3 are recorded together with the first 8 words each pointer argument points at; the native call is compared
 * (as many arguments as the function declares) and every difference is LOGGED (the first few are printed with the report): a wrong argument is often the first visible
 * sign of a value that was computed differently -- or of a call that retail makes without loading its arguments. */
#define ARG_WORDS 2                                                         /* words compared at the target of a pointer argument */
static unsigned ev_arg[EV_SCR_MAX][4];
static unsigned ev_pt[EV_SCR_MAX][4][8];
static unsigned char ev_ptv[EV_SCR_MAX];                                    /* bit j: argument j is a pointer with a recorded pointee */
#define ARGMIS_MAX 64
static struct { unsigned idx; int arg, word; unsigned nat, org; } g_argmis[ARGMIS_MAX];
static int n_argmis, g_argmis_total;
static unsigned n_ev_int, g_ev_idx;
static int g_trace_on;                                                      /* 0 off, 1 recording the original, 2 comparing the native game */
static unsigned g_div_idx, g_div_got, g_div_want;
extern unsigned g_ls_ignore_enter;
static unsigned nat_key[8192], nat_val[8192], ps1_key[8192];
static int nat_ar[8192];
static int n_nat, n_ps1;
static int no_event_name(const char* n) {                                   /* BIOS veneers: compiler-generated calls to them exist only natively */
    static const char* const list[] = { "memset", "psyq_api_memcpy", "memmove", "bzero", "bcopy", "strlen", "strcpy", "strcmp", "strcat", "memchr", "rand", "srand",
                                        "sin_1", "psyq_gte_csqrt_kernel", 0 };                    /* the last two: helpers of the natively replaced libgte, only ever called from inside it */
    int i;
    for (i = 0; list[i]; i++) if (streq(n, list[i])) return 1;
    return 0;
}
static void sort_pairs(unsigned* k, unsigned* v, int n) {                   /* insertion sort by key (v may be 0) */
    int i, j;
    for (i = 1; i < n; i++) { unsigned kk = k[i], vv = v ? v[i] : 0; for (j = i - 1; j >= 0 && k[j] > kk; j--) { k[j + 1] = k[j]; if (v) v[j + 1] = v[j]; } k[j + 1] = kk; if (v) v[j + 1] = vv; }
}
static void sort_triples(unsigned* k, unsigned* v, int* w, int n) {         /* insertion sort by key, v and w follow */
    int i, j;
    for (i = 1; i < n; i++) { unsigned kk = k[i], vv = v[i]; int ww = w[i]; for (j = i - 1; j >= 0 && k[j] > kk; j--) { k[j + 1] = k[j]; v[j + 1] = v[j]; w[j + 1] = w[j]; } k[j + 1] = kk; v[j + 1] = vv; w[j + 1] = ww; }
}
static void build_event_tables(void) {
    int m, i;
    n_nat = n_ps1 = 0;
    for (m = 0; m <= g_nactive; m++) {
        int mod = m == 0 ? 0 : g_active[m - 1];
        for (i = 0; i < g_modules[mod].nfns; i++) {
            const struct mfn* f = &g_modules[mod].fns[i];
            if (no_event_name(f->name) || n_ps1 >= 8192) continue;
            ps1_key[n_ps1++] = f->addr;
            if (f->native && n_nat < 8192) { nat_key[n_nat] = (unsigned)f->native; nat_val[n_nat] = f->addr; nat_ar[n_nat] = f->arity; n_nat++; }
        }
    }
    sort_pairs(ps1_key, 0, n_ps1);
    sort_triples(nat_key, nat_val, nat_ar, n_nat);
}
static int find_key(const unsigned* k, int n, unsigned x) { int lo = 0, hi = n - 1; while (lo <= hi) { int mid = (lo + hi) / 2; if (k[mid] == x) return mid; if (k[mid] < x) lo = mid + 1; else hi = mid - 1; } return -1; }
static int arg_is_ptr(unsigned v) { return (v >= 0x80000000u && v < 0x80200000u) || (v >= 0x1f800000u && v < 0x1f800400u) || (v >= THREAD_STACK_WINDOW && v < THREAD_STACK_WINDOW + THREAD_STACK_WINDOW_BYTES); }
static int arg_in_stack(unsigned v) { return (v >= 0x801f0000u && v < 0x80200000u) || (v >= MAIN_STACK_WINDOW && v < MAIN_STACK_WINDOW + MAIN_STACK_BYTES); }
static int arg_pointee_ok(unsigned v) {                                     /* data, stack or scratchpad (code bytes differ by construction: trampolines) */
    int r;
    unsigned a = v & ~3u;
    if (v >= 0x1f800000u && v < 0x1f800400u) return a + 32 <= 0x1f800400u;
    if (a >= THREAD_STACK_WINDOW && a + 32 <= THREAD_STACK_WINDOW + THREAD_STACK_WINDOW_BYTES) return 1;      /* a native thread's stack */
    if (a + 32 > 0x80200000u) return 0;
    if (arg_in_stack(v)) return 1;
    for (r = 0; r < ndata; r++) if (a >= data_lo[r] && a + 32 <= data_hi[r]) return 1;
    return 0;
}
static unsigned orig_word(unsigned a) { return a >= 0x1f800000u && a < 0x1f800400u ? *(unsigned*)(cpu.scratch + (a - 0x1f800000u)) : *(unsigned*)(interp_ram + (a & 0x1fffff)); }
static void ls_event_hook(r3k_t* c, unsigned target) {                      /* the interpreter: every jal/jalr/j target that is a function entry */
    if (g_trace_on != 1) return;
    if (untraced_caller(c->r[31])) return;                                  /* a call made from inside the natively replaced libgte */
    if (find_key(ps1_key, n_ps1, target) < 0) return;
    if (n_ev_int < EV_MAX) {
        if (n_ev_int < EV_SCR_MAX) {
            int k;
            for (k = 0; k < 8; k++) ev_scr[n_ev_int][k] = ((unsigned*)c->scratch)[SCRATCH_FIRST_COMPARED + k];
            for (k = 0; k < 4; k++) ev_w[n_ev_int][k] = g_watch[k].addr ? *(unsigned*)(interp_ram + (g_watch[k].addr & 0x1fffff)) : 0;
            ev_ptv[n_ev_int] = 0;
            for (k = 0; k < 4; k++) {
                unsigned v = c->r[4 + k];
                int q;
                ev_arg[n_ev_int][k] = v;
                if (arg_is_ptr(v) && arg_pointee_ok(v)) { ev_ptv[n_ev_int] |= (unsigned char)(1u << k); for (q = 0; q < 8; q++) ev_pt[n_ev_int][k][q] = orig_word((v & ~3u) + 4u * (unsigned)q); }
            }
        }
        ev_a0[n_ev_int] = c->r[4]; ev_a1[n_ev_int] = c->r[5]; ev_ra[n_ev_int] = c->r[31]; ev_int[n_ev_int++] = target;
    }
}
void __attribute__((no_instrument_function)) __cyg_profile_func_enter(void* fn, void* site) {
    int k;
    unsigned ps1;
    (void)site;
    if (g_trace_on != 2) return;
    if (g_ls_ignore_enter) { g_ls_ignore_enter = 0; return; }
    k = find_key(nat_key, n_nat, (unsigned)fn);
    if (k < 0) return;                                                      /* a helper that is not a game function */
    ps1 = nat_val[k];
    if (g_ev_idx >= n_ev_int || ev_int[g_ev_idx] != ps1) {
        g_div_idx = g_ev_idx; g_div_got = ps1; g_div_want = g_ev_idx < n_ev_int ? ev_int[g_ev_idx] : 0;
        g_hle_native.sync_reason = HLE_SYNC_DIVERGED;
        ls_switch(&g_game_esp, g_driver_esp);                               /* stop the native game right here; the driver reports */
        return;
    }
    if (g_ev_idx < EV_SCR_MAX) {                                            /* the scratchpad's first words must be what the original had when it entered the same call */
        int j;
        for (j = 0; j < 4 && g_watch[j].addr; j++) if (*(unsigned*)g_watch[j].addr != ev_w[g_ev_idx][j]) {     /* ... and so must the words given with -Watch */
            g_div_watch = (unsigned)j + 1; g_div_w_native = *(unsigned*)g_watch[j].addr; g_div_idx = g_ev_idx; g_div_got = g_div_want = ps1;
            g_hle_native.sync_reason = HLE_SYNC_DIVERGED;
            ls_switch(&g_game_esp, g_driver_esp);
            return;
        }
        for (j = 0; j < 8; j++) if (((unsigned*)0x1f800000u)[SCRATCH_FIRST_COMPARED + j] != ev_scr[g_ev_idx][j]) {
            for (j = 0; j < 8; j++) g_div_scr_native[j] = ((unsigned*)0x1f800000u)[SCRATCH_FIRST_COMPARED + j];
            g_div_scratch = 1; g_div_idx = g_ev_idx; g_div_got = g_div_want = ps1;
            g_hle_native.sync_reason = HLE_SYNC_DIVERGED;
            ls_switch(&g_game_esp, g_driver_esp);
            return;
        }
        {   /* the arguments (cdecl: on the caller's frame, right above its return address) */
            unsigned* fp = (unsigned*)__builtin_frame_address(1);
            int ar = nat_ar[k], lim = ar < 0 ? 0 : (ar > 4 ? 4 : ar);
            for (j = 0; j < lim; j++) {
                unsigned na = fp[2 + j], oa = ev_arg[g_ev_idx][j];
                int bad = 0, word = -1;
                unsigned nv = na, ov = oa;
                if (arg_is_ptr(na) && arg_is_ptr(oa)) {
                    if (na != oa && !stackish_equal(na, oa)) bad = 1;                               /* two addresses in the same stack are "equal" (the frames differ) */
                    if (!bad && (ev_ptv[g_ev_idx] & (1u << j)) && arg_pointee_ok(na)) {
                        int q;
                        for (q = 0; q < ARG_WORDS; q++) { unsigned x = *(unsigned*)((na & ~3u) + 4u * (unsigned)q), y = ev_pt[g_ev_idx][j][q]; if (x != y) { bad = 1; word = q; nv = x; ov = y; break; } }
                    }
                } else if (na != oa) bad = 1;
                if (bad) {
                    int slot = g_argmis_total % ARGMIS_MAX;                                             /* a ring: the differences nearest to the divergence are the interesting ones */
                    g_argmis_total++;
                    g_argmis[slot].idx = g_ev_idx; g_argmis[slot].arg = j; g_argmis[slot].word = word; g_argmis[slot].nat = nv; g_argmis[slot].org = ov;
                    n_argmis = g_argmis_total < ARGMIS_MAX ? g_argmis_total : ARGMIS_MAX;
                }
            }
        }
    }
    g_ev_idx++;
}
void __attribute__((no_instrument_function)) __cyg_profile_func_exit(void* fn, void* site) { (void)fn; (void)site; }
static void print_fn_ps1(unsigned a) { func_at(a); }
static void print_argmis(void) {
    int i;
    if (!g_argmis_total) return;
    out("  argument differences at calls before this point (native vs original; "); outnum(g_argmis_total); out(" in all, the last "); outnum(n_argmis); out("):\n");
    for (i = 0; i < n_argmis; i++) {
        int slot = g_argmis_total <= ARGMIS_MAX ? i : (g_argmis_total + i) % ARGMIS_MAX;
        outnum(g_argmis[slot].idx); out("  "); print_fn_ps1(ev_int[g_argmis[slot].idx]); out("  a"); outnum(g_argmis[slot].arg);
        if (g_argmis[slot].word >= 0) { out(" -> word "); outnum(g_argmis[slot].word); out(" of the pointee"); }
        out(":  native "); outhex(g_argmis[slot].nat); out("  original "); outhex(g_argmis[slot].org); out("\n");
    }
}
static void replay_crash_context(void) {
    unsigned k;
    out("  the native game crashed in the replayed frame after "); outnum(g_ev_idx); out(" calls (the original's call sequence, function entries):\n");
    for (k = g_ev_idx > 14 ? g_ev_idx - 14 : 0; k < g_ev_idx + 3 && k < n_ev_int; k++) { out(k < g_ev_idx ? "    #" : "    (next) #"); outnum(k); out("  "); print_fn_ps1(ev_int[k]); out("\n"); }
    print_argmis();
}
static void report_divergence(unsigned idx, unsigned got, unsigned want, int native_short) {
    unsigned k;
    print_argmis();
    out("  call sequence of the frame (the original's, function entries):\n");
    for (k = idx > 12 ? idx - 12 : 0; k < idx; k++) { out("    #"); outnum(k); out("  "); print_fn_ps1(ev_int[k]); out("\n"); }
    if (g_div_watch) {
        out("  the watched word "); out(g_watch[g_div_watch - 1].name); out(" differs on entering call #"); outnum(idx); out(" ("); print_fn_ps1(got); out("): native "); outhex(g_div_w_native);
        out(", original "); outhex(ev_w[idx][g_div_watch - 1]); out("\n");
        out("  => call #"); outnum(idx ? idx - 1 : 0); out(" ("); if (idx) print_fn_ps1(ev_int[idx - 1]); out("), its callees, or its caller's code right after it, wrote it differently\n");
    } else
    if (g_div_scratch) {
        unsigned j;
        out("  the SCRATCHPAD differs on entering call #"); outnum(idx); out(" ("); print_fn_ps1(got); out("):\n");
        for (j = 0; j < 8; j++) if (g_div_scr_native[j] != ev_scr[idx][j]) { out("    scratchpad+0x"); outhex((SCRATCH_FIRST_COMPARED + j) * 4); out("  native "); outhex(g_div_scr_native[j]); out("  original "); outhex(ev_scr[idx][j]); out("\n"); }
        out("  => call #"); outnum(idx ? idx - 1 : 0); out(" ("); if (idx) print_fn_ps1(ev_int[idx - 1]); out("), its callees, or its caller's code right after it, wrote the scratchpad differently\n");
    } else
    if (native_short) {
        out("  the native game finished the frame after "); outnum(idx); out(" calls; the original's next call was "); print_fn_ps1(want); out("\n");
    } else {
        out("  FIRST DIFFERENCE at call #"); outnum(idx); out(":\n    native   called "); print_fn_ps1(got); out("\n    original called ");
        if (idx < n_ev_int) print_fn_ps1(want); else out("(nothing: the original's frame had only "), outnum(n_ev_int), out(" calls)");
        out("\n  => the function that ran just before (#"); outnum(idx ? idx - 1 : 0); out(", "); if (idx) print_fn_ps1(ev_int[idx - 1]); out(") or its callee made a different decision\n");
    }
}
#else
/* the game is always compiled with -finstrument-functions (so that -Replay needs no rebuild of the objects): without a replay the hooks do nothing */
void __attribute__((no_instrument_function)) __cyg_profile_func_enter(void* fn, void* site) { (void)fn; (void)site; }
void __attribute__((no_instrument_function)) __cyg_profile_func_exit(void* fn, void* site) { (void)fn; (void)site; }
#endif

/* ------------------------------------------------------------------------------------------------ the driver */
static gte_state_t gte_of[2];                                               /* [0] original, [1] native: the software GTE is one global, swapped at every switch */
static int run_native(void) {                                               /* -> sync reason, or -1 when the native game returned from main() */
    g_gte = gte_of[1];
    g_hle_native.sync_reason = HLE_SYNC_NONE;
    sys3(27, 40, 0, 0);                                                         /* alarm(40): a native frame that never reaches its next VSync is reported with a backtrace */
    ls_switch(&g_driver_esp, g_game_esp);
    sys3(27, 0, 0, 0);
    gte_of[1] = g_gte;
    return g_native_dead ? -1 : g_hle_native.sync_reason;
}
static int g_orig_rc;
static int run_orig(void) {                                                 /* -> sync reason, or 0 when the interpreter faulted / ran out of steps (g_orig_rc) */
    g_gte = gte_of[0];
    hle_i.stop = 0; hle_i.sync_reason = HLE_SYNC_NONE;
    g_orig_rc = r3k_run(&cpu, STEP_BUDGET);
    gte_of[0] = g_gte;
    return hle_i.stop ? hle_i.sync_reason : 0;
}
/* compare the calls the two machines made into the HLE this frame (the platform-layer traffic) */
static void print_trace_entry(const hle_trace_entry_t* e) {
    out(e->name); out("("); outhex(e->a[0]); out(", "); outhex(e->a[1]); out(", "); outhex(e->a[2]); out(", "); outhex(e->a[3]); out(") pointee-hash "); outhex(e->a[4]);
}
/* two DrawOTag calls hashed differently: the first packet that differs (each machine's dump of the call: {address, length, words...} per packet) */
static const struct hle_otdump* otdump_of(const hle_t* h, unsigned idx) {
    unsigned k;
    for (k = 0; k < h->otdump_n && k < HLE_OTDUMPS; k++) if (h->otdump[k].trace_idx == idx) return &h->otdump[k];
    return 0;
}
static void print_otdump_diff(unsigned idx) {
    const struct hle_otdump* dn = otdump_of(&g_hle_native, idx);
    const struct hle_otdump* dy = otdump_of(&hle_i, idx);
    unsigned pn = 0, py = 0, np = 0, k;
    if (!dn || !dy) { out("    (no packet dump kept for this call)\n"); return; }
    while (pn < dn->n && py < dy->n) {
        unsigned ln = dn->w[pn + 1], ly = dy->w[py + 1], same = ln == ly;
        for (k = 0; same && k < ln; k++) if (dn->w[pn + 2 + k] != dy->w[py + 2 + k]) same = 0;
        if (!same) {
            out("    packet #"); outnum(np); out(" differs:\n      native   at 0x"); outhex(dn->w[pn]); out(" len "); outnum(ln); out(":");
            for (k = 0; k < ln; k++) { out(" "); outhex(dn->w[pn + 2 + k]); }
            out("\n      original at 0x"); outhex(dy->w[py]); out(" len "); outnum(ly); out(":");
            for (k = 0; k < ly; k++) { out(" "); outhex(dy->w[py + 2 + k]); }
            out("\n");
            if (np) { out("      the packet before (native) at 0x"); outhex(dn->w[pn - 0]); out("\n"); }
            return;
        }
        pn += 2 + ln; py += 2 + ly; np++;
    }
    out("    the packets are the same for the first "); outnum(np); out(" (native has "); out(pn < dn->n ? "more" : "no more"); out(", original has "); out(py < dy->n ? "more" : "no more"); out(")\n");
}
static int compare_traces(void) {
    unsigned i, n = hle_i.trace_n < g_hle_native.trace_n ? hle_i.trace_n : g_hle_native.trace_n;
    for (i = 0; i < n; i++) {
        const hle_trace_entry_t* x = &g_hle_native.trace[i];
        const hle_trace_entry_t* y = &hle_i.trace[i];
        int k, same = streq(x->name, y->name);
        for (k = 0; k < 5; k++) if (x->a[k] != y->a[k]) same = 0;
        if (!same) {
            unsigned c0 = i > 8 ? i - 8 : 0, c;
            for (c = c0; c < i; c++) { out("    #"); outnum(c); out(" (both) "); print_trace_entry(&hle_i.trace[c]); out("\n"); }
            out("  HLE call #"); outnum(i); out(" differs:\n    native   "); print_trace_entry(x); out("\n    original "); print_trace_entry(y); out("\n");
            if (streq(x->name, "DrawOTag") && streq(y->name, "DrawOTag")) print_otdump_diff(i);
            return 1;
        }
    }
    if (hle_i.trace_n != g_hle_native.trace_n) {
        out("  the machines made a different number of HLE calls: native "); outnum(g_hle_native.trace_n); out(", original "); outnum(hle_i.trace_n);
        if (i < hle_i.trace_n) { out("; original's next: "); print_trace_entry(&hle_i.trace[i]); }
        if (i < g_hle_native.trace_n) { out("; native's next: "); print_trace_entry(&g_hle_native.trace[i]); }
        out("\n");
        return 1;
    }
    return 0;
}
/* where the interpreter is (used when the original does not reach its next VSync: a loop in the original itself) */
#ifdef REPLAY_FRAME
/* which functions the original called how often in the frame (a runaway frame shows its loop here) */
static void print_event_histogram(void) {
    static unsigned hist[8192];
    unsigned k, top;
    int i, best;
    for (i = 0; i < n_ps1; i++) hist[i] = 0;
    for (k = 0; k < n_ev_int; k++) { int j = find_key(ps1_key, n_ps1, ev_int[k]); if (j >= 0) hist[j]++; }
    out("  most frequent calls of the original's frame:\n");
    for (top = 0; top < 14; top++) {
        best = -1;
        for (i = 0; i < n_ps1; i++) if (hist[i] && (best < 0 || hist[i] > hist[best])) best = i;
        if (best < 0) break;
        out("    "); outnum(hist[best]); out("  x  "); func_at(ps1_key[best]); out("\n");
        hist[best] = 0;
    }
}
#endif
static void print_peeks(void) {
    int i;
    for (i = 0; g_peek[i].addr; i++) {
        unsigned k;
        out("  "); out(g_peek[i].name); out(" @0x"); outhex(g_peek[i].addr); out(" (original):");
        for (k = 0; k < g_peek[i].words; k++) { if (k % 8 == 0) out("\n    "); outhex(*(unsigned*)(interp_ram + ((g_peek[i].addr + 4 * k) & 0x1fffff))); out(" "); }
        out("\n");
    }
}
static void print_orig_state(void) {
    int i, k;
    unsigned w;
    print_peeks();
    out("  the original is in "); func_at(cpu.cur_pc); out(" after "); outnum((long)cpu.steps); out(" steps; ra="); func_at(cpu.r[31]); out("\n  registers:");
    for (i = 2; i < 32; i++) { if (i % 6 == 2) out("\n    "); out("r"); outnum(i); out("="); outhex(cpu.r[i]); out(" "); }
    out("\n");
    out("  the original's call stack (return addresses found on its stack):\n");
    for (i = 0; i < 0x100; i++) {                                           /* scan 1 KiB above sp for words that point into game functions */
        unsigned a = cpu.r[29] + 4u * (unsigned)i, v;
        int m;
        const struct mfn* f = 0;
        if (a >= 0x80200000u) break;
        v = *(unsigned*)(interp_ram + (a & 0x1fffff));
        if (v < 0x80010000u || v >= 0x801e0000u || (v & 3)) continue;
        f = fn_at(v - 8, 0);
        for (m = 0; !f && m < g_nactive; m++) f = fn_at(v - 8, g_active[m]);
        if (f) { out("    sp+0x"); outhex(4u * (unsigned)i); out("  "); out(f->name); out("+0x"); outhex(v - 8 - f->addr); out("\n"); }
    }
    for (i = 0; i < 6; i++) {
        unsigned rv = i < 4 ? cpu.r[4 + i] : cpu.r[16 + i - 4];
        if (rv >= 0x80000000u && rv < 0x801f0000u) { out("  words at "); outhex(rv); out(": "); for (k = 0; k < 8; k++) { w = *(unsigned*)(interp_ram + ((rv + 4u * (unsigned)k) & 0x1fffff)); outhex(w); out(" "); } out("\n"); }
    }
}
static void report_stubs(void) {
    int i, n = 0;
    for (i = 0; i < g_stub_count; i++) if (g_stub_hits[i]) n++;
    out("native calls into yaml functions that have no native definition (stubs returning 0): "); outnum(n); out(" distinct, "); outnum(g_stub_calls); out(" calls\n");
    for (i = 0; i < g_stub_count; i++) if (g_stub_hits[i]) { out("    "); out(g_stub_names[i]); out(" x"); outnum(g_stub_hits[i]); out("\n"); }
}

/* a DrawOTag whose ordering-table chain left RAM: the table is corrupt (report which machine, where) */
static void report_bad_ot(void) {
    hle_t* hs[2]; const char* names[2];
    int i;
    hs[0] = &g_hle_native; hs[1] = &hle_i; names[0] = "native"; names[1] = "original";
    for (i = 0; i < 2; i++) if (hs[i]->bad_ot_addr) {
        out("  DrawOTag on the "); out(names[i]); out(" machine: the ordering-table chain from 0x"); outhex(hs[i]->bad_ot_head); out(" is broken at 0x"); outhex(hs[i]->bad_ot_addr);
        out(" (tag word 0x"); outhex(hs[i]->bad_ot_tag); out(")\n");
        hs[i]->bad_ot_addr = 0;
    }
}
static int main_test(void) {
    int frame, rn, ro, diffs;
    hle_platform_t pa, pb;
    pa.ctx = (void*)"original"; pa.r8 = ia_r8; pa.w8 = ia_w8; pa.write_bytes = ia_wb; pa.call = ia_call; pa.read_sector = read_sector; pa.frame = ia_frame; pa.log = log_call; pa.is_overlay = is_overlay_lba; pa.interp_reexec = 1; pa.valid = ia_valid; pa.stack_lo = pa.stack_hi = 0;
    pb.ctx = (void*)"native"; pb.r8 = nb_r8; pb.w8 = nb_w8; pb.write_bytes = nb_wb; pb.call = nb_call; pb.read_sector = read_sector; pb.frame = nb_frame; pb.log = log_call; pb.is_overlay = is_overlay_lba; pb.interp_reexec = 0; pb.valid = nb_valid; pb.stack_lo = MAIN_STACK_WINDOW; pb.stack_hi = MAIN_STACK_WINDOW + MAIN_STACK_BYTES;
    hle_init(&hle_i, &pa);
    hle_init(&g_hle_native, &pb);

    /* --- run the ORIGINAL from the entry point to main() --- */
    g_main_addr = addr_of("main");
    cpu.hle = interp_hle;
    cpu.tick = interp_tick;
    install_hle_hooks(0);
    r3k_hle_add(&cpu, g_main_addr);
#ifdef SCENARIO_TITLE
    if (g_scn_addr) r3k_hle_add(&cpu, g_scn_addr);
#endif
    cpu.r[29] = 0x801fff00u;
    cpu.pc = addr_of("__SN_ENTRY_POINT"); cpu.npc = cpu.pc + 4;
    g_orig_rc = r3k_run(&cpu, STEP_BUDGET);
    if (!g_at_main) { out("the original did not reach main(): rc "); outnum(g_orig_rc); out(" at "); func_at(cpu.cur_pc); out("\n"); return 1; }
    cpu.fault = 0; unhook(g_main_addr);
    out("original is at main() after "); outnum((long)cpu.steps); out(" instructions; copying its RAM to the native image and starting the native game\n");
    copy_data_interp_to_native();
    *(volatile unsigned char*)0x80010ba8u = 0xc3;                             /* battle_bin_entrypoint: retail has 1024 nops and a `jr ra` there (a deprecated overlay entry); natively: ret */
    g_bios_rand_seed = cpu.bios_rand_seed;
    gte_of[0] = gte_of[1] = g_gte;
    hle_i.cd_reads = 0; hle_i.cd_sectors = 0; hle_i.calls = 0;
    start_native_game();

    /* --- frame by frame --- */
    for (frame = 1; frame <= (int)g_frames; frame++) {
        g_cur_frame = frame;
        g_hle_native.pad_mask = hle_i.pad_mask = pad_at((unsigned)frame);                  /* both machines see the same controller */
        null_page_close();
        {   int q;
            for (q = 0; q < g_npokes; q++) {
                if (g_pokes[q].done || *(unsigned*)(interp_ram + (g_pokes[q].caddr & 0x1fffff)) != g_pokes[q].cval) continue;
                *(volatile unsigned*)g_pokes[q].addr = g_pokes[q].val;                       /* native RAM */
                *(unsigned*)(interp_ram + (g_pokes[q].addr & 0x1fffff)) = g_pokes[q].val;    /* the interpreter's RAM */
                g_pokes[q].done = g_pokes[q].repeat ? 0 : 1;                                  /* a repeating poke fires whenever its condition holds again */
                out("  [frame "); outnum(frame); out("] poke: *0x"); outhex(g_pokes[q].addr); out(" = 0x"); outhex(g_pokes[q].val); out(" (when *0x"); outhex(g_pokes[q].caddr); out(" == 0x"); outhex(g_pokes[q].cval); out(")\n");
            }
        }
        hle_i.trace_n = g_hle_native.trace_n = 0; hle_i.trace_lost = g_hle_native.trace_lost = 0;
        hle_i.otdump_n = g_hle_native.otdump_n = 0;
#ifdef REPLAY_FRAME
        if (frame == REPLAY_FRAME) {                                             /* record the original's calls, then compare the native game's live */
            build_event_tables(); n_ev_int = 0; g_ev_idx = 0; g_ls_ignore_enter = 0;
            cpu.trace_calls = 1; cpu.pending_call = 0; cpu.event_hook = ls_event_hook; g_trace_on = 1;
            ro = run_orig();
            cpu.trace_calls = 0; cpu.pending_call = 0; cpu.event_hook = 0; g_trace_on = 2; g_crash_context = replay_crash_context;
            if (!ro) { out("FRAME "); outnum(frame); out(": the ORIGINAL did not reach its next VSync (rc "); outnum(g_orig_rc); out(") -- a loop in the original itself, not a native divergence\n"); print_event_histogram(); print_orig_state(); report_stubs(); return 1; }
#ifdef DUMP_AROUND
            {   /* the calls around the first entry of one function (-DumpAround name) */
                unsigned k, first = 0xffffffffu, target = 0;
                int mm;
                for (mm = 0; mm <= g_nactive && !target; mm++) target = addr_in(mm == 0 ? 0 : g_active[mm - 1], DUMP_AROUND);
                for (k = 0; k < n_ev_int; k++) if (ev_int[k] == target) { first = k; break; }
                if (first == 0xffffffffu) out("  the function to dump around was never called in this frame\n");
                else for (k = first > 30 ? first - 30 : 0; k < first + 60 && k < n_ev_int; k++) { out("    #"); outnum(k); out("  "); print_fn_ps1(ev_int[k]); out("  a0=0x"); outhex(ev_a0[k]); out(" a1=0x"); outhex(ev_a1[k]); out("  from "); func_at(ev_ra[k] - 8); out("\n"); }
            }
#endif
#ifdef EVENT_DUMP
            { unsigned k; out("  the original's first calls of the frame (function, a0, a1):\n"); for (k = 0; k < (unsigned)EVENT_DUMP && k < n_ev_int; k++) { out("    #"); outnum(k); out("  "); print_fn_ps1(ev_int[k]); out("  a0=0x"); outhex(ev_a0[k]); out(" a1=0x"); outhex(ev_a1[k]); out("  from "); func_at(ev_ra[k] - 8); out("\n"); } }
#endif
            out("replay of frame "); outnum(frame); out(": the original made "); outnum(n_ev_int); out(" calls to game functions; now the native game runs it under comparison\n");
            rn = run_native();
            g_trace_on = 0;
            if (rn == HLE_SYNC_DIVERGED) { out("FRAME "); outnum(frame); out(": the native game's control flow differs from the original's\n"); report_divergence(g_div_idx, g_div_got, g_div_want, 0); report_stubs(); return 2; }
            if (rn >= 0 && g_ev_idx < n_ev_int) { out("FRAME "); outnum(frame); out(": the native game made fewer calls than the original\n"); report_divergence(g_ev_idx, 0, ev_int[g_ev_idx], 1); report_stubs(); return 2; }
            if (rn >= 0) { out("  the native game made exactly the same sequence of calls\n"); print_argmis(); }
        } else {
            rn = run_native();
            if (rn < 0) { out("native main() returned before frame "); outnum(frame); out("\n"); return 1; }
            ro = run_orig();
        }
        if (rn < 0) { out("native main() returned before frame "); outnum(frame); out("\n"); return 1; }
#else
        rn = run_native();
        if (rn < 0) { out("native main() returned before frame "); outnum(frame); out("\n"); return 1; }
        ro = run_orig();
#endif
        if (!ro) { out("original stopped without syncing before frame "); outnum(frame); out(": rc "); outnum(g_orig_rc); out(" at "); func_at(cpu.cur_pc); out(" (steps "); outnum((long)cpu.steps); out(")\n"); report_stubs(); return 1; }
        g_where = ro == HLE_SYNC_OVERLAY ? "overlay load" : "VSync";
        if (rn != ro) { out("FRAME "); outnum(frame); out(": the machines synced for different reasons: native "); outnum(rn); out(", original "); outnum(ro); out("\n"); report_stubs(); return 2; }
        diffs = compare_ram(0);
        report_bad_ot();
        if (compare_traces()) { out("FRAME "); outnum(frame); out(": the machines' calls into the HLE differ (RAM differs in "); outnum(diffs); out(" words)\n"); if (diffs) compare_ram(SHOW_DIFFS); report_stubs(); return 2; }
        if (diffs || compare_scratch()) {
            out("FRAME "); outnum(frame); out(": RAM differs in "); outnum(diffs); out(" words (native vs original)"); if (compare_scratch()) out(" and in the scratchpad"); out("; first ones:\n");
            compare_ram(SHOW_DIFFS);
            print_scratch_diffs(SHOW_DIFFS);
            out("native VSync count "); outnum(g_hle_native.frame_counter); out(", original "); outnum(hle_i.frame_counter);
            out("; CD reads native "); outnum(g_hle_native.cd_reads); out(" original "); outnum(hle_i.cd_reads); out("; original steps "); outnum((long)cpu.steps); out("\n");
            report_stubs();
            return 2;
        }
        if (ro == HLE_SYNC_OVERLAY) {
            int mi = module_at(hle_i.sync_arg2), k, j, installed;
            out("frame "); outnum(frame); out(": the game loads a code overlay ("); out(mi >= 0 ? g_modules[mi].file : "?"); out(", "); outnum(hle_i.sync_arg1); out(" sectors at LBA "); outnum(hle_i.sync_arg2);
            out(" -> 0x"); outhex(hle_i.sync_arg0); out("); RAM identical; original steps "); outnum((long)cpu.steps); out("\n");
            if (g_hle_native.sync_arg0 != hle_i.sync_arg0 || g_hle_native.sync_arg1 != hle_i.sync_arg1 || g_hle_native.sync_arg2 != hle_i.sync_arg2) { out("BUT the two machines asked for different reads\n"); return 2; }
            /* the new module evicts every active module whose address range it overlaps */
            for (k = 0; k < g_nactive; k++) {
                const struct module* a = &g_modules[g_active[k]];
                unsigned alo = a->load, ahi = a->load + a->sectors * 2048u, blo = g_modules[mi].load, bhi = g_modules[mi].load + g_modules[mi].sectors * 2048u;
                if (alo < bhi && blo < ahi) { uninstall_module(g_active[k]); remove_hle_hooks(g_active[k]); for (j = k; j + 1 < g_nactive; j++) g_active[j] = g_active[j + 1]; g_nactive--; k--; }
            }
            g_active[g_nactive++] = mi;
            installed = install_module(mi);
            j = install_hle_hooks(mi);
            build_ranges();
            out("  module "); out(g_modules[mi].name); out(": "); outnum(installed); out(" of "); outnum(g_modules[mi].nfns); out(" functions have native code, "); outnum(j); out(" taken over by the HLE; "); outnum(ndata); out(" data ranges compared from now on\n");
            if (!installed) { out("  no native code for this module -- stopping (the machines agreed up to here)\n"); report_stubs(); return 0; }
        } else
        if (g_hle_native.frame_counter != hle_i.frame_counter || g_hle_native.cd_reads != hle_i.cd_reads) { out("FRAME "); outnum(frame); out(": VSync/CD counters differ\n"); return 2; }
        report_watch(frame);
#ifdef WHERE_FRAME
        if (frame == WHERE_FRAME) { out("the original at the VSync of frame "); outnum(frame); out(":\n"); print_orig_state(); }
#endif
        if (frame % 25 == 0 || frame == 1) {
            out("frame "); outnum(frame); out(": RAM identical ("); outnum(ndata); out(" data ranges; original steps "); outnum((long)cpu.steps); out(", CD reads "); outnum(hle_i.cd_reads); out(", stub calls "); outnum(g_stub_calls); out(")\n");
        }
        if (hle_i.reexec) { hle_i.reexec = 0; cpu.fault = 0; cpu.pc = cpu.fault_pc; cpu.npc = cpu.pc + 4; }   /* VSync(n): the remaining blanks are the same call again */
        else { cpu.fault = 0; cpu.pc = cpu.r[31]; cpu.npc = cpu.pc + 4; }         /* the HLE'd VSync returns to its caller */
    }
    out("== "); outnum((long)g_frames); out(" frames: RAM identical at every VSync\n");
    report_stubs();
    return 0;
}

void _start(void) {
    int bad;
    long n, n_tramp;
    if (!map_fixed(0x80000000u, 0x200000u)) { out("mmap of the RAM image FAILED\n"); sys3(1, 1, 0, 0); }
    map_fixed(0x1f800000u, 0x1000u);                                         /* scratchpad (the native game may use it); I/O registers stay unmapped: a touch is a crash report */
    if (!map_fixed(THREAD_STACK_WINDOW, THREAD_STACK_WINDOW_BYTES)) { out("mmap of the thread-stack window FAILED\n"); sys3(1, 1, 0, 0); }
    if (!map_fixed(THUNK_BASE, (THUNK_BYTES + 0xfffu) & ~0xfffu)) { out("mmap of the coverage thunks FAILED\n"); sys3(1, 1, 0, 0); }
    if (map_fixed(0u, NULL_PAGE_BYTES)) { g_null_page_mapped = 1; g_null_page_open = 1; null_page_close(); }
    install_fault_handlers();
    n = load_file("/disc/SCUS_942.21", (unsigned char*)0x8000f800u);
    build_ranges();
    n_tramp = install_module(0);                                              /* first: compiler-generated calls to memset/memcpy resolve to PS1 addresses (trampolines) */
    load_file("/disc/SCUS_942.21", interp_ram + (0x8000f800u & 0x1fffff));
    out("SCUS_942.21: "); outnum(n); out(" bytes\n");
    g_disc_fd = (int)sys3(5, (long)"/disc.bin", 0, 0);
    r3k_reset(&cpu, interp_ram);
    cpu.zero_frames = 1;                                                      /* uninitialised locals read as 0 on both machines (the native game is built with -ftrivial-auto-var-init=zero) */
    outnum(n_tramp); out(" trampolines of the main executable (native image only), "); outnum(ndata); out(" data ranges compared\n");
#ifdef SCENARIO_TITLE
    g_scn_addr = addr_of(SCENARIO_FN);
    if (g_scn_addr) {                                                         /* point the trampoline of that function at the wrapper */
        unsigned char* tp = (unsigned char*)g_scn_addr;
        tp[0] = 0xe9; *(unsigned*)(tp + 1) = (unsigned)scn_wrapper - (g_scn_addr + 5);
        out("scenario title: main_item_init_new_game_inventory will set g_main_system_frontend_world_result = 5 on both machines\n");
    }
#endif
    gte_reset();
    load_run_config();
    bad = main_test();
    report_null_sites();
    write_coverage();
    sys3(1, bad, 0, 0);
}
