#!/usr/bin/env python3
"""hazards.py ERR_DIR OUT.md -- aggregate GCC undefined-behaviour warnings (from probe mode m32W) into a report.

Each warning is a *candidate* hazard for a native port: on the PS1 the value read/index used is deterministic by accident;
natively it is undefined. gcc -O2 has false positives (especially -Wmaybe-uninitialized), so read this as a worklist."""
import re, sys
from collections import Counter, defaultdict
from pathlib import Path

err_dir, out = Path(sys.argv[1]), sys.argv[2]
rx = re.compile(r'^(?P<file>[^:\s]+):(?P<line>\d+):(?P<col>\d+): warning: (?P<msg>.*) \[(?P<flag>-W[\w=-]+)\]\s*$')
seen = set()
by_flag = defaultdict(list)
for p in sorted(err_dir.glob('*.err')):
    for l in p.read_text(errors='replace').splitlines():
        m = rx.match(l)
        if not m:
            continue
        key = (m['file'], m['line'], m['col'], m['flag'], m['msg'])
        if key in seen:
            continue
        seen.add(key)
        by_flag[m['flag']].append((m['file'], int(m['line']), m['msg']))

lines = ['# Undefined-behaviour candidates for the native port',
         '', 'Generated by `port\\tools\\hazards.py` from `gcc -m32 -O2` on the portified sources. '
         'Candidates only: PS1 behaviour is deterministic by accident; natively these are undefined. '
         'gcc has false positives (esp. maybe-uninitialized).', '']
tot = sum(len(v) for v in by_flag.values())
lines.append(f'**{tot} distinct warnings**')
lines.append('')
lines.append('| flag | count | files |')
lines.append('|---|---|---|')
for flag, items in sorted(by_flag.items(), key=lambda kv: -len(kv[1])):
    lines.append(f'| `{flag}` | {len(items)} | {len({f for f, _, _ in items})} |')
lines.append('')
for flag, items in sorted(by_flag.items(), key=lambda kv: -len(kv[1])):
    lines.append(f'## `{flag}` ({len(items)})')
    per_file = Counter(f for f, _, _ in items)
    lines.append('Top files: ' + ', '.join(f'`{Path(f).name}` ({n})' for f, n in per_file.most_common(8)))
    lines.append('')
    for f, ln, msg in sorted(items)[:60]:
        lines.append(f'- `{f}:{ln}` {msg}')
    if len(items) > 60:
        lines.append(f'- … {len(items) - 60} more')
    lines.append('')
Path(out).write_text('\n'.join(lines), encoding='utf-8')
print(f'{tot} distinct warnings -> {out}')
for flag, items in sorted(by_flag.items(), key=lambda kv: -len(kv[1])):
    print(f'  {flag:<28} {len(items):>5} in {len({f for f, _, _ in items}):>4} files')
